project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  title: "eReefs tutorials"
  navbar: 
    background: "#335b84"
    logo: images/navbar_logo.png
    right:
      - href: https://www.r-project.org/
        text: "{{< fa brands r-project >}}"
      - href: https://www.python.org/
        text: "{{< fa brands python >}} python"
      - text: "   "
      - href: "https://github.com/bfordAIMS/ereefs-tutorials"
        icon: "github"
    collapse-below: sm

format:
  html:
    theme: 
      light: [flatly, theme_changes_light.scss]
      dark: [darkly, theme_changes_dark.scss]
    highlight-style: atom-one
    css: styles.css
    toc: true

execute:
  freeze: auto
  code-fold: true
