project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  title: "eReefs tutorials"
  navbar:
    title: "eReefs tutorials"
    logo: https://www.ereefs.org.au/assets/images/logos/ereefs_logo.svg
    background: "#335b84"
    pinned: false
    right:
      - href: https://www.ereefs.org.au/
        text: Home
      - href: https://www.r-project.org/
        text: "{{< fa brands r-project >}}"
      - href: https://www.python.org/
        text: "{{< fa brands python >}} python"
      - text: "   "
      - href: "https://github.com/open-AIMS/ereefs-tutorials"
        icon: "github"
    collapse-below: sm
  page-footer:
    background: "#335b84"
    center:
      - text: Collaborators
        href: https://www.ereefs.org.au/about/collaborators.html
      - text: Funders
        href: https://www.ereefs.org.au/about/funders.html
      - text: Privacy Policy
        href: https://www.csiro.au/en/About/Access-to-information/Privacy
      - text: Legal & Disclaimer
        href: https://www.csiro.au/en/about/Policies/Legal/Legal-notice

format:
  html:
    theme: flatly
    highlight-style: atom-one
    css: styles.css
    toc: true

execute:
  freeze: auto
  code-fold: true
