{
  "hash": "edbd360821e84804ff3049e8d1d2ac78",
  "result": {
    "markdown": "---\ntitle: \"Times Series Plots {{< fa brands r-project >}}\"\n---\n\n::: {.cell}\n\n:::\n\n\n# Topics covered {-}\n\n* Extracting eReefs data using the online data extraction tool\n* Setting up `R` and `RStudio` and importing the eReefs data\n* Interactive `leaflet` maps with reef boundaries\n* Basic time series plots in `ggplot2`\n* Time series plots with data grouped by year in `ggplot2`\n* Interactive plots with `plotly`\n* Exploring two-dimensional relationships with scatter plots in `ggplot2`\n\n\n# Motivating problem\n\nHeat waves occur in the shallow waters of the Great Barrier Reef (GBR) in much the same way that they occur on land. When the waters gets too hot for too long, corals become sick and can eventually die (as a result of coral bleaching). As the Earth continues to warm under a changing climate, these heat waves are becoming hotter, longer, and more frequent, threating the survival of the GBR as we know it. \n\nDifferent coral populations along the GBR are adapted to the long-term temperature ranges which may be considered normal for the area in which they live. In general, this means that the northern populations are better able to handle warmer waters than their southern counterparts. Some of these adaptations are encoded in the their genomes and we can imagine that the spread of these warm-adpated genes to the southern GBR would confer some level of resilience to future heat wave events. \n\nHowever, major ocean currents along the GBR bifurcate, i.e. split, off the coast of Cairns (@fig-currents), creating prevailing northward currents in the waters to the north. It has been suggested that these northward currents may act as a genetic barrier for corals, preventing coral larvae from travelling south and spreading their genes into the Southern GBR. \n\nWe wish to examine this phenomena on a finer scale to get a sense of how strong and persistant this genetic barrier may be.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![eReefs 2016 yearly mean temperatures (left) and currents (right) for the Great Barrier Reef showing north-to-south temperature gradient and current bifurcation north-east of Cairns (shown in red and orange).](images/gbr4_2016_bifurcation.png){#fig-currents fig-align='center' width=75%}\n:::\n:::\n\n\n\n# Data extraction\n\nData was extracted from the [eReefs GBR Hydrological Model (4km) v2.0](https://ereefs.aims.gov.au/ereefs-aims/gbr4/temp-wind-salt-current) using the online [data extraction tool](https://extraction.ereefs.aims.gov.au/extract-data) for a single point approximately 60 km south of Lizard Island (shown in @fig-site). For this point we extracted the daily aggregated data for the northward current at a depth of 0.5 m (as coral larvae generally travel in the top of the water column) and the northward windspeed (to see if the wind may be a key driver of current speed and direction). Both of these variables have the units of meters per second (m/s), where a positive value indicates the speed of the wind to the north, and a negative value, to the south. We extracted all data between 1 September 2010 - 1 September 2022. \n\nThis data can be downloaded [here](https://extraction.ereefs.aims.gov.au/data/2211.f8f2a18). **!Replace link after upload (so github tutorial link can be added to data page)!**\n\n\n# R & R Studio setup\n\n1. Download and install `R` (the programming language) and R Studio (the integrated development environment) following the instructions [here](https://posit.co/download/rstudio-desktop/).\n\n2. [Download the git repository for this tutorial](https://github.com/bfordAIMS/ereefs-tutorials/tree/main/tutorials/r/time-series-plot-r), and unzip the folder in a suitable place on your hard drive.\n\n3. Open R Studio and create a new project: File > New Project > Existing Directory > Browse > select the unzipped git tutorial folder created in step 2. \n\n4. Open the file `tutorial__time_series.Rmd` and run the code chunk below by clicking the `<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:green;overflow:visible;position:relative;\"><path d=\"M73 39c-14.8-9.1-33.4-9.4-48.5-.9S0 62.6 0 80V432c0 17.4 9.4 33.4 24.5 41.9s33.7 8.1 48.5-.9L361 297c14.3-8.7 23-24.2 23-41s-8.7-32.2-23-41L73 39z\"/></svg>`{=html} button in the top right corner. Chunks can also be run be pressing ctrl+shift+enter and sections of code (e.g. half a line, a single line, multiple lines) can be run by selecting the section and pressing ctrl+enter (replace ctrl with cmd on Mac). \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Install the R packages required for this tutorial\nrequired_packages <- c(\"readr\", \"tidyverse\", \"janitor\", \"leaflet\", \"lubridate\", \"plotly\", \"fontawesome\", \"htmltools\")\ninstalled_packages <- installed.packages()[, \"Package\"] # list of pkgs already installed\nnot_yet_installed <- required_packages[!(required_packages %in% installed_packages)]\nif (length(not_yet_installed) > 0) install.packages(not_yet_installed) # install pkgs not yet installed\n```\n:::\n\n\n\n# Importing data\n\nFirst we need to load in the R packages we will use for this tutorial. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load R packages:\nlibrary(readr) # faster data importing\nlibrary(tidyverse) # a suite of packages including dplyr, tidyr, ggplot2, stringr\nlibrary(janitor) # create better variable names\nlibrary(leaflet) # making interactive maps\nlibrary(lubridate) # easier handling of dates and times \nlibrary(plotly) # making interactive plots\nlibrary(fontawesome) # to put icons in R markdown html\nlibrary(htmltools) # for styling interactive outputs\n\n# Load our custom function to create time series ggplots with data grouped by year \n# (or a given period <= 12 years) \nsource(\"ggTS_byYear.R\") # we will go through this function later in the tutorial\n```\n:::\n\n\nThe data we have extracted from eReefs is in a CSV file. We will import the data into `R` using the `readr` package's `read_csv` function (which is much faster at reading in large datasets compared to `R`'s base function `read.csv`). We will then apply the `janitor` package's `clean_names` function, which will format the variable names in a way which is much more convenient for use in `R`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Import data:\ndata_raw <- read_csv(\"data/eReefsData.csv\")\ndata <- data_raw %>% clean_names()\ndata %>% glimpse() # take a 'glimpse' at our data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 8,766\nColumns: 12\n$ aggregated_date_time <dttm> 2010-09-01, 2010-09-01, 2010-09-02, 2010-09-02, …\n$ variable             <chr> \"wspeed_v\", \"v\", \"wspeed_v\", \"v\", \"wspeed_v\", \"v\"…\n$ depth                <dbl> 99999.9, -0.5, 99999.9, -0.5, 99999.9, -0.5, 9999…\n$ site_name            <chr> \"site_a\", \"site_a\", \"site_a\", \"site_a\", \"site_a\",…\n$ latitude             <dbl> -15.25, -15.25, -15.25, -15.25, -15.25, -15.25, -…\n$ longitude            <dbl> 145.46, 145.46, 145.46, 145.46, 145.46, 145.46, 1…\n$ mean                 <dbl> 6.17655035, 0.11174639, 5.97394102, 0.11343298, 7…\n$ median               <dbl> 6.26913939, 0.14671343, 6.04144896, 0.11044985, 7…\n$ p5                   <dbl> 5.346766602, 0.000353042, 5.447607187, 0.07272162…\n$ p95                  <dbl> 7.231647611, 0.200932400, 6.545938471, 0.20063861…\n$ lowest               <dbl> 5.2204528552, 0.0000000000, 5.3579356785, 0.06825…\n$ highest              <dbl> 7.231647611, 0.200932400, 6.545938471, 0.20063861…\n```\n:::\n\n```{.r .cell-code}\n# Print the range of dates in our data:\npaste(\"Date range:\", min(data$aggregated_date_time), \"to\", max(data$aggregated_date_time))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Date range: 2010-09-01 to 2022-08-31\"\n```\n:::\n:::\n\n\nHere we can see that we have data for the `wspeed_v` (northward wind velocity) and `v` (northward current velocity) for our single site `site_a` with the coordinates (145.46, -15.25). As we have downloaded the daily aggregated data, we get the mean, median, p5 (5th percentile), p95 (95th percentile), lowest and highest values for each day between 1 September 2010 through 31 August 2022.\n\n# Interactive GBR maps\n\nLets have a closer look at the site for which we have extracted the eReefs data by plotting it on an interactive `leaflet` map along with the GBR reef features. The GBR reef features layer is located in the [eAtlas Web Mapping Service (AIMS)](https://eatlas.org.au/data/uuid/71127e4d-9f14-4c57-9845-1dce0b541d8d). A list of other layers available in this server can be found [here](https://maps.eatlas.org.au/maps/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage).\n\nYou can find out more about creating `leaflet` maps in `R` [here](https://rstudio.github.io/leaflet/).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get unique coordinates from data (in this case only one set of lat/lon)\nsite_coords <- data.frame(\n  lat = unique(data_raw$Latitude), \n  lon = unique(data_raw$Longitude)\n)\n# Plot coordinates on a leaflet map\nsite_map <- site_coords %>% \n    leaflet( # create a blank leaflet map\n      options = leafletOptions(attributionControl=FALSE) # remove the 'leaflet' watermark\n    ) %>% \n    addTiles() %>% # adds a basemap (OpenStreetMap by default)\n    addMarkers() %>% # add a marker at the given coordinates\n    addScaleBar()\n\n# Add the GBR reef features (WMS layer) to the map\nsite_map <- site_map %>% \n    addWMSTiles(\n      baseUrl = \"https://maps.eatlas.org.au/maps/wms?\", # Link to WMS server\n      layers = c(\"ea:GBR_GBRMPA_GBR-features\"), # Names of layers (located in the WMS server) to display\n      options = WMSTileOptions(format = \"image/png\", transparent = TRUE)\n    ) \n                \n# Display the map centred at our site\nsite_map %>% \n    setView(lng = site_coords$lon[1], lat = site_coords$lat[1], zoom = 9)\n```\n\n::: {#fig-site .cell-output-display}\n```{=html}\n<div class=\"leaflet html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-0f0356036a0418a1fb33\" style=\"width:75%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0f0356036a0418a1fb33\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"attributionControl\":false},\"calls\":[{\"method\":\"addTiles\",\"args\":[\"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\",null,null,{\"minZoom\":0,\"maxZoom\":18,\"tileSize\":256,\"subdomains\":\"abc\",\"errorTileUrl\":\"\",\"tms\":false,\"noWrap\":false,\"zoomOffset\":0,\"zoomReverse\":false,\"opacity\":1,\"zIndex\":1,\"detectRetina\":false,\"attribution\":\"&copy; <a href=\\\"https://openstreetmap.org\\\">OpenStreetMap<\\/a> contributors, <a href=\\\"https://creativecommons.org/licenses/by-sa/2.0/\\\">CC-BY-SA<\\/a>\"}]},{\"method\":\"addMarkers\",\"args\":[-15.25,145.46,null,null,null,{\"interactive\":true,\"draggable\":false,\"keyboard\":true,\"title\":\"\",\"alt\":\"\",\"zIndexOffset\":0,\"opacity\":1,\"riseOnHover\":false,\"riseOffset\":250},null,null,null,null,null,{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]},{\"method\":\"addScaleBar\",\"args\":[{\"maxWidth\":100,\"metric\":true,\"imperial\":true,\"updateWhenIdle\":true,\"position\":\"topright\"}]},{\"method\":\"addWMSTiles\",\"args\":[\"https://maps.eatlas.org.au/maps/wms?\",null,null,{\"styles\":\"\",\"format\":\"image/png\",\"transparent\":true,\"version\":\"1.1.1\",\"layers\":\"ea:GBR_GBRMPA_GBR-features\"}]}],\"limits\":{\"lat\":[-15.25,-15.25],\"lng\":[145.46,145.46]},\"setView\":[[-15.25,145.46],9,[]]},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nInteractive map showing site for which eReefs data was extracted.\n:::\n:::\n\n\n# Time series plots\n\n## Basic\n\nSince we are interested in gaining some insight into the possibility of northern coral larvae migrating southward through our site, we should have a look at the north-south current velocity data. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata %>% \n  filter(variable == \"v\") %>% # select the current variable\n  ggplot(aes(x = aggregated_date_time, y = mean)) + # and plot the daily mean\n  geom_line(alpha=0.7) + # specify a line graph of the mean\n  geom_abline(slope = 0, intercept = 0, color = \"red\", linewidth = 1) + # add a line a y=0\n  scale_x_datetime(date_breaks = \"1 year\", date_labels = \"%Y\") + # show only years on x-axis\n  theme_bw(base_size=13) + \n  labs(x = \"Year\", y = \"Northward current velocity (m/s)\")\n```\n\n::: {.cell-output-display}\n![Time series plot of daily mean northward current velocity.](time_series_plot_r_files/figure-html/fig-ts-1.png){#fig-ts fig-align='center' width=75%}\n:::\n:::\n\n\nHere we see that there does appear to be a cyclical pattern to the northward current at our site, with southward currents (i.e. negative northward current) primarily in the wet season. This is great news, as this is when coral spawning occurs! \n\nHowever, in order to get a better idea of what is happening, we should have a closer look at the data for the coral spawning period of roughly October - January. \n\n## Advanced\n\nWe wish to produce the plot below, looking at all our data in an approximate coral spawning season of October through January, for each of the years in our data.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Times series plot of daily mean northward current velocity during October through January for each year 2010-11 to 2021-22.](time_series_plot_r_files/figure-html/fig-tsOctFeb-1.png){#fig-tsOctFeb fig-align='center' width=75%}\n:::\n:::\n\n\nThe first thing we can note, from this plot, is that it is very cluttered, making it difficult to detect any clear trend in our data. However, before we investigate this further, lets look at how the plot was made. \n\nUnfortunately, there does not seem to be any out-of-the-box or intuitive ways to plot a given season (i.e. period less than 12 months) for multiple years in `ggplot`. However, we can hack a solution by writing a function called `ggTS_byYear` which creates a fake date variable where all the data is converted to be in the same year and then plots this fake date along the x-axis and groups the data based on the real date. This function is defined below. \n\nYou can copy and paste this function into your script if you would just like to get to using it straight away. However, it is also heavily commented should you wish to customise it further, troubleshoout an errors you are encountering when using it, or fix any unforeseen bugs which may be present. \n\n*Note:* if troubleshooting, consider using `R` function [`browser`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/browser). \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n########################################################################\n## PLOT TIME SERIES BY YEAR OVER A GIVEN PERIOD <= 12 MONTHS          ##\n## ------------------------------------------------------------------ ##\n## RETURNS: ggplot object (without geoms)                             ##\n## REQUIRES: ggplot, dplyr, magritter, lubridate                      ##\n## ------------------------------------------------------------------ ##\n## Example:                                                           ##\n##    salinity_time_series_plot <-                                    ##\n##      ggTS_byYear(                                                  ##\n##        data = eReefs_data,                                         ##\n##        date_col_name = date_time,                                  ##\n##        response_col_name = daily_mean_salinity,                    ##\n##        start_month = 6,                                            ##\n##        end_month = 5                                               ##\n##      ) +                                                           ##\n##      geom_line() +                                                 ##\n##      labs(y = \"Daily mean salinity\", x = \"Date\", colour = \"Year\")  ##\n##                                                                    ##\n## Warning: not designed for plot periods > 12 months                 ##\n##                                                                    ##\n## Function concept: fake year(s) is used to put data for all years   ##\n##                   on same x-axis, where as plot period denotes     ##\n##                   real year(s)pertaining to the data dates         ##\n##                                                                    ##\n## Note: x-axis major breaks are months, if a different period is     ##\n##       required, use the ggplot2::scale_x_datetime() function       ##\n########################################################################\nggTS_byYear <- function(\n    data, # dataframe with POSIX dates and continuous response\n    date_col_name, # the name of the dataframe column with the date variable to plot\n    response_col_name, # the name of the dataframe column with the response variable to plot\n    start_month = 1, # lower time series limit (default January)\n    end_month = 12, # upper time series limit (default December)\n    minor_breaks_period = \"1 day\" # the period for the graph's x-axis minor breaks (e.g. 1 week, 1 day)\n) {\n  # SETUP\n  require(ggplot2)  # for plotting\n  require(magrittr) # source of the pipe (%>%) function\n  require(dplyr)    # data manipulation\n  require(lubridate) # date handling\n  fake_year <- 0001 # fake year used to have all dates over same period (grouped by real year)\n  \n  # APPEND VARIABLES TO DATA FOR USE IN PLOTTING\n  data = data %>%  \n    mutate(\n      datetime = as_datetime({{date_col_name}}), # Ensure dates in POSIX format\n      year = year(datetime), # Create columns for real year and\n      month = month(datetime) # real month\n    )\n  \n  # THE CASE WHEN THE PLOT PERIOD IS WITHNIN A SINGLE CALENDER YEAR (e.g. June 2016 - Nov 2016)\n  if (start_month <= end_month) {\n    # Get x-axis breaks and labels:\n    plot_months = c(start_month:(end_month+1)) # vector of months to plot (including end_month)\n    plot_breaks = make_datetime(fake_year, plot_months) # x-axis major breaks at each month\n    # Assign data to plot periods and fake years and filter out data not needed:\n    data <- data %>% \n      mutate(\n        # Plot period is within the real year (e.g. June 2016 - October 2016) \n        plot_period_label = paste(year), # data for all months pertain to respective year\n        dummy_date = update(datetime, year = fake_year) # all data plotted over fake year (e.g. 0001)\n      ) %>% \n      filter(month >= start_month & month <= end_month)\n  }\n  \n  # THE CASE WHEN THE PLOT PERIOD IS SPREAD ACROSS TWO CALENDER YEARS (e.g. Nov 2016 - June 2017)\n  if (start_month > end_month) {\n    # Get x-axis breaks and labels\n    plot_months_y1 = c(start_month:12) # a vector of months to plot in the former year\n    plot_months_y2 = c(1:(end_month+1)) # a vector of months to plot in the latter year\n    plot_months = c(plot_months_y1, plot_months_y2)\n    plot_breaks <- c(\n      make_datetime(fake_year, plot_months_y1),\n      make_datetime(fake_year+1, plot_months_y2)\n    ) \n    # Assign data to plot periods (i.e. based on real dates), create the fake date \n    # (using fake_year and fake_year +1), and filter out data not needed:\n    data <- data %>% \n      mutate(\n        # Plot period crosses two calender years, therefore\n        # data for months prior to start_month pertain to preceding plot period\n        plot_period_start = ifelse(month >= start_month, year, year-1), \n        plot_period_end = plot_period_start+1,\n        plot_period_label = paste(plot_period_start, substr(plot_period_end, 3, 4), sep = '-'), \n        # Dummy dates: months after start_month plotted in fake year (e.g. 0001), months prior plotted in 0002\n        dummy_year = ifelse(month >= start_month, fake_year, fake_year + 1), \n        dummy_date = update(datetime, year = dummy_year)\n      ) %>% \n      filter(month >= start_month | month <= end_month)\n  }\n  \n  # CREATE X-AXIS (DATES) BREAK LABELS \n  # If end_month is 12 (December), plot_months ends at 13 (January of next year)\n  plot_months <- replace(plot_months, plot_months==13, 1) # Change 13 to 1\n  break_labels <- month.abb[plot_months]\n\n  # CREATE PLOT\n  ts_plot <- data %>% \n    ggplot(aes(x = dummy_date, y = {{response_col_name}}, group = plot_period_label, colour = plot_period_label)) + \n    labs(x = \"Date\", y = \"Response\",  colour = \"Year\") + \n    theme_bw() + \n    scale_x_datetime(breaks = plot_breaks, labels = break_labels, date_minor_breaks = minor_breaks_period)\n\n  return(ts_plot)\n}\n```\n:::\n\n\nNow we have our function definition, lets see it in action. Recall that our previous plot was quite cluttered, which made it difficult to discern any trends in the data. So this time, let's plot for just the month of October. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata %>% \n  filter(variable == \"v\") %>%\n  ggTS_byYear(aggregated_date_time, mean, start_month = 10, end_month = 10) + \n  geom_line(linewidth = 0.7) + \n  geom_abline(slope = 0, intercept = 0, linewidth = 0.8) + \n  labs(y = \"Northward current velocity (m/s)\")\n```\n\n::: {.cell-output-display}\n![Times series plot of daily mean northward current velocity during October for each year 2010 to 2021.](time_series_plot_r_files/figure-html/fig-tsOct-1.png){#fig-tsOct fig-align='center' width=75%}\n:::\n:::\n\n\nThis is significantly easier to digest. However, there is still a lot going on, and sometimes we may wish to see more than a single month at a time. \n\n# Interactive plots\n\nIn `R`, we can create interactive plots with the [`plotly`](https://plotly.com/r/) package. \n\nWith a `plotly` interactive plot, we can view individual years, compare subsets of the years, and zoom in on our data and pan across. As this interactivity is a virtue of the html file format, `plotly` plots have limited application (e.g. cannot be used for reports). However, they do allow us to explore our data very easily and intuitively. \n\nLet's plot our data across an entire year and use the zoom and pan features to explore in more detail. Let's plot the graph from September through August, as this aligns with the dates for the data we have extracted. Note that the years are selectable/deselectable from the plot legend, where we can also double click a year to toggle between all years and just the single year, and that when zooming we drag the cursor to zoom and double click to zoom back out.\n\nWe will initially show only the years 2015-16 and 2021-22, as this provides a nice instance of high variability in the northward current in different years. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create a ggplot and turn it into a plotly plot\nplotSepSep <- data %>% \n  filter(variable == \"v\") %>%\n  ggTS_byYear(aggregated_date_time, mean, start_month=9, end_month=8) +\n  geom_line(linewidth = 0.7) + \n  geom_abline(slope = 0, intercept = 0, linewidth = 0.5) + \n  labs(y = \"Northward current velocity (m/s)\") + \n  theme(legend.position=\"top\")\n\nplotSepSep %>% \n  ggplotly(tooltip = \"none\") %>% # don't show any information on hover (alternative: \"mean\" would show mean current)\n  style(visible = \"legendonly\", traces = c(1:5, 7:11))  # don't show years 2010-2014 & 2016-2020 initially\n```\n\n::: {#fig-plotlySepSep .cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-ce5e7cae22a28bc3c9fb\" style=\"width:85%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ce5e7cae22a28bc3c9fb\">{\"x\":{\"data\":[{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.111746389179969,0.113432977843326,0.26994329217072,0.116586038875548,0.0445734174347757,-0.0677314963613104,-0.0889949403891975,0.0682758111307093,0.0769753150547232,0.029957241426387,-0.013615929227597,0.116177253342045,0.192377102574503,0.196556050497791,0.0678871247230463,-0.120251493040846,-0.0790205881587239,-0.0848283928749765,-0.0223441240640668,0.0864926041196802,0.197330336340929,0.243142954905222,0.27291092092553,0.29529567657814,0.254545585472412,0.218808222246877,0.237993643671892,0.108391613080326,-0.0947647556722957,-0.0745873388727904,0.179790074158036,0.343534930859007,0.369831182486938,0.293008715298009,0.236453897569163,0.17207687878145,0.108601646808859,0.0973443554864593,0.127037815111718,0.233332466640895,0.318297481170652,0.335258805552093,0.32915375916566,0.215120377761495,-0.0212695342985162,-0.0392151088681498,0.0907357384617559,0.164391534669559,0.274594643490527,0.384103058540873,0.467675398109722,0.450241422713523,0.31674289953089,0.321765547821808,0.279887629564115,0.207143337669944,0.219792394314135,0.270009533001449,0.301850676425589,0.274089625659178,0.269244156133651,0.21650111227279,0.139862389501884,0.132492909660029,0.214729747058361,0.271726822791593,0.2218757178251,0.215411182351693,0.17023564500711,0.271520577950654,0.277052257885376,0.256794554602873,0.278681878226251,0.317640873887718,0.300024779270057,0.195809805965193,-0.0306065233428532,-0.13600669158715,-0.290339403775485,-0.148912503472636,0.266186992990202,0.312565552199572,0.326835355263176,0.350499685415569,0.373764293005062,0.399457992500442,0.369023997972385,0.328662141477101,0.183729991168801,0.0248275791925227,-0.036867323528924,0.00680560351348531,0.123512666669855,0.170510253382339,0.0654150748456607,-0.075216462359036,-0.215734296993766,-0.24679900326485,-0.177320579748374,0.0507787748515963,0.208462619565004,0.128867831739821,0.0375695052329254,-0.138716393062664,-0.182895897859964,-0.123371857349323,-0.136414113253471,-0.125121852890529,-0.19629102395288,-0.302471139647285,-0.318524381789158,-0.078593690006761,0.111957666220135,0.325565012403442,0.3755463964392,0.221495142244384,-0.185710251035493,-0.375729270607414,-0.325313609124258,-0.320992996379953,-0.0883253514885667,0.236400184912076,0.319091729991809,0.226792812490721,0.137134610191024,-0.0198050752773238,-0.068643494937854,0.0057252992904361,0.046078129473883,0.120447108320316,0.114418995842789,0.0417024527201487,-0.0956891863113019,-0.0734648623418354,-0.0972968481837662,-0.109039789331351,-0.0867683655831416,-0.17704727855294,-0.209529037730127,-0.206477712087667,-0.32939059880307,-0.191913725514824,0.0209164591471414,0.429119874979751,0.585163651192789,0.317336394008629,0.175016829184421,0.0897566607668984,0.121430491111529,0.358398260222041,0.412923905878435,0.42659620471588,0.181344396455651,0.106544398723359,0.205966581667493,-0.308671988213968,-0.0891548360634221,-0.14663908802244,-0.103233129618464,0.194759452088493,0.32186889897955,0.361762846877645,0.331941620314531,0.360624378237597,0.329641880662159,0.252524209053841,0.095781399669406,0.109987463649232,0.234275873676888,0.241941432043598,0.291251752324841,0.370207742060039,0.354492618178468,0.302645366038982,0.319970919042789,0.333294318071681,0.432476841834111,0.478825232550448,0.358798872960081,0.137117397879316,0.00624632384065925,-0.105933671544222,-0.0111785210602153,0.069813899110265,0.21996470786663,0.281425912879392,0.257533600524595,0.217030915658966,0.340129394375369,0.365651644616019,0.290116512587504,0.257378922328591,0.269986863388702,0.398309115560938,0.372048671032537,0.303892676746989,0.215451090357707,0.22427588395009,0.199626579542006,0.1200620652289,-0.0112072854699427,-0.211761438258621,-0.232525966246708,-0.21102415258411,-0.120147821842687,-0.0273024314226762,0.174325710875678,0.317835320802682,0.517009520079017,0.462720170204294,0.391680308325019,0.301074556368863,0.310657092346605,0.395672243998312,0.586667970113326,0.642910654532636,0.609349909056061,0.596750761148963,0.568070080489749,0.533221595933651,0.480153081618073,0.385552572362916,0.242535380274531,0.172848650621017,0.160492827015682,0.222064301693328,0.181354383127284,0.139369122375237,0.195507625126638,0.277416715561858,0.349879170291168,0.401972506555594,0.31338319749244,0.20144142981182,0.127870811550014,0.280796429194763,0.423172342396119,0.44335452525618,0.420692296374953,0.434744311797212,0.440457337129839,0.375042624658528,0.284690531063476,0.179011929319644,0.136778749771266,0.0826869046619873,0.0771687862776668,0.232017514437559,0.271248954502712,0.306580078249043,0.124966467425228,0.101976606361467,0.162485152069309,0.179550391158454,0.253437997385042,0.214808133050038,0.270078715726845,0.350846017327761,0.451355947978626,0.471292710510631,0.381324270650892,0.350315170857794,0.327476087236741,0.271716532176051,0.231612676827862,0.0510202793830314,0.0733321130335302,0.160694589473763,0.229278676806116,0.254822022430864,0.3241506191252,0.360270637417025,0.299353502188209,0.264508954480451,0.195898127649343,0.188062255321992,0.224931419890118,0.259945252794148,0.250685597590394,0.227951836277814,0.201425389836548,0.198213704331031,0.212054144580428,0.302290263824346,0.372216048843794,0.320439545530128,0.292848329164904,0.289496043814136,0.296375860061114,0.260391707532802,0.201183181756076,0.158581144874358,0.150882095418981,0.194630144316612,0.196884576885864,0.30862335749252,0.413299442308971,0.402930640542997,0.3953003823218,0.37769686171288,0.342352295732252,0.361551152119505,0.452641855557106,0.497774880010921,0.380816414236552,0.292412624373791,0.297806873780196,0.349363706086691,0.272019257712655,0.255749853460549,0.19531915026982,0.257202648512684,0.31164626714462,0.315588179875037,0.345518715929596,0.338224887423366,0.356845253945223,0.380894722174625,0.394345877548613,0.350238761269724,0.376833188492911,0.272728017585176,0.199934262920336,0.204103061711066,0.22755802794257,0.221335322130903,0.145010955476801,0.14198862345083,0.205766551769878,0.267893113094805,0.309561609717447,0.361830416733572,0.327650761485416,0.292441175524256,0.28896479947805,0.309213946239186,0.320073524926156,0.277431173582232,0.333092457509196,0.304324123557136,0.284862333088606,0.168065892692101,-0.0232107232055007,-0.134888093225233,-0.210075504536917,0.0239220151783315,0.193928635215414,0.270575267527228,0.336187542500252,0.283788210739465,0.164914273810533,0.0555788789417425,0.0662254584577157,0.0544413107970669,0.0948876420367526,0.272253049907396,0.4015533674297,0.424580169044775,0.403083295083687,0.347451823805335,0.274424714453923,0.0474915724679486,0.018098654578963,0.00194186331912172,0.00558262862775498],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2010-11\",\"legendgroup\":\"2010-11\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.244524395232512,0.334096851347856,0.438426635402592,0.376750330607931,0.33906972208947,0.232801024638451,0.137651225634871,0.0475945461969543,-0.155784718793988,-0.0659849314385149,0.0777887561736479,0.131151003222279,0.266306772888445,0.36080724674072,0.361259155539601,0.371348503878837,0.318645315918182,0.235583608411879,0.0942271242474486,-0.137198491254695,-0.163868903312398,0.0170507657349466,0.253771542205683,0.236757634095562,0.12893162933008,-0.158003528594238,-0.327805847327256,-0.211221122520295,-0.358279544069211,-0.437380397939501,-0.414994499457038,-0.1587036680191,-0.0816330202914122,-0.0847021154786737,-0.0313220460056385,-0.0938986853745678,-0.244497160461509,-0.369230829558435,-0.403585698283082,-0.400093633572493,-0.410457539671099,-0.40517294312181,-0.300705948807664,-0.269746293989485,-0.285733954835114,-0.411637516588032,-0.200046308299262,0.222609493463124,0.428729939630666,0.448783949208187,0.40668524989432,0.303663773803978,0.199059943477526,0.0801669601348847,0.0435651132285354,0.0228052001194241,0.021384569330035,0.0525263192074883,0.0871043425510949,0.0434261140440711,0.040812348343072,0.12492165063699,0.150475171771085,0.133149043117826,0.0154928602779607,0.00595527182039355,0.0594201022701696,0.154455698951742,0.172802170162996,0.26370477523653,0.26471622926513,0.189183756526617,0.174412527650999,0.187070433475579,0.163631495712298,0.185744245950875,0.17598120446103,0.0864485385994343,0.0404132618338355,-0.0232930581473013,-0.0463635621694347,-0.0853170152255447,-0.177057785040812,-0.196934519414942,-0.161114474853991,-0.157976864515492,-0.179935893615287,-0.124174582977808,-0.110588906051229,-0.0889431450975466,0.105700373946471,0.179979907311666,0.0705832960931749,0.0451357687245029,0.129082925594152,0.0910338015129718,0.0167578845737148,-0.19563695768392,-0.339161279592699,-0.420895762714345,-0.395546258141896,-0.252205595165628,-0.385292042011086,-0.340961807756234,-0.316217608264111,-0.115189810116159,0.079173070275183,0.380238190643093,0.315652128135281,0.239798374309915,0.182346492447241,0.206532717594933,0.238014444950723,0.223366376349666,0.0986187174341029,-0.0548182435558936,-0.217245638349875,-0.32490827025527,-0.209620978343184,-0.20215008950738,-0.00299123211545122,0.310021157787535,0.338103020056368,0.2828005579034,0.168091896167472,0.111527097060207,0.0212605939847908,-0.125264832398399,-0.264691372944905,-0.130433505083454,-0.195282171854243,-0.272218944732072,-0.329145981697387,-0.345212429990029,-0.322628309997124,-0.319679418809794,-0.245412521968072,-0.172984152484986,-0.160932136664279,-0.104806821885186,-0.0936551687537293,-0.0588850933780726,0.048340398400797,0.0681455857363136,0.00372024294309762,-0.105353368335203,-0.265357184975518,-0.307324513286416,-0.389354696923176,-0.395642522093942,-0.370397764232047,-0.31541183119139,-0.255917585479693,-0.220851783520166,-0.278847889895759,-0.0571514731179492,0.0835485504318623,0.143355280294928,0.0454700550398761,-0.0433730796125959,0.0521431627496928,-0.0897178340799599,-0.087263710682428,0.0141623674839454,0.126903768998376,0.148310450553698,0.17126800421967,0.17541378406223,0.245704316786402,0.362292707954605,0.386937488526148,0.277482969406401,0.12046919161192,-0.0859909210623727,-0.216492985417414,-0.137224046062941,-0.00171067298725198,0.160600645499954,0.26586780459951,0.248629499642089,0.26370575222053,0.1825013993207,0.0709106413824317,-0.135420594951195,-0.183342681096857,-0.0692858621350264,-0.0327133973610415,-0.042710430727448,-0.158061415739963,-0.187113227785185,0.0678162733586278,0.137015851529176,0.25070463755195,0.195615251688533,0.173500094800008,0.187371437558977,0.0601907243812558,-0.175736252905681,-0.350227167871483,-0.382100060297633,-0.414165316628871,-0.41124401308003,-0.207420066550925,-0.165204723095566,-0.163161193431831,0.0634929042347732,0.016947461351256,0.368314334509213,0.519493117769111,0.43437479155014,0.361796178516208,0.325396093857154,0.319196499114567,0.30355636330383,0.24240686580852,0.184859944026563,0.050719787326852,-0.0252157049224843,0.105307616894701,0.212285988273364,0.190671284443519,0.163674382583649,0.162400892592202,0.279147937635637,0.429278608102696,0.506015602203909,0.508023521825961,0.53360710391045,0.378604974413698,0.316858902033629,0.324214837719273,0.320722417882771,0.327009361027727,0.255217903851875,0.198169562060484,0.202586110458599,0.19718117934085,0.183641857681351,0.176931079960159,0.208830920923844,0.356509608733257,0.334055023913771,0.418295605168647,0.443506341015932,0.428585238509283,0.383789883162209,0.392852713057314,0.269386361951638,0.249155268493063,0.268686738694253,0.265489243250588,0.333853916250799,0.375679059268612,0.352223906782276,0.307747715226314,0.2921118400559,0.297170851509891,0.3135848462289,0.337493323438094,0.368201606947852,0.343757313572119,0.325807613981545,0.331440342730521,0.259115236012347,0.382229838684003,0.357760717215821,0.271756944231651,0.307663416991362,0.504219848314275,0.442827836706601,0.457211861515982,0.44397177100589,0.462625796163377,0.416841045218428,0.306857036082687,0.306565012340731,0.21651608960797,0.0465627900259108,0.0290289377099696,0.113250718666062,0.189365261488709,0.227500805595715,0.225445447834355,0.200985517569239,0.179231176884124,0.0698012843893779,-0.03337358550831,-0.0400531234316217,0.0796264088162404,0.23273165102461,0.286955392037215,0.243725581533232,0.183181916155773,0.16634205678595,0.112467627503073,0.179149868480582,0.271827606814396,0.411436806050954,0.460941103770561,0.386767924523189,0.263616634582663,0.175950618886874,0.061297986050957,-0.139710180984494,-0.0158012952795336,0.255331481350256,0.368691307329656,0.373468624944157,0.462289278230237,0.524623207876575,0.448740594252976,0.353058561077228,0.369526408263304,0.297715305082891,0.476176286581674,0.248407790627386,0.0989309568129234,-0.211832071433117,-0.0416743681015609,0.450511926633309,0.457770122901235,0.291444142696314,0.0867909451262612,0.182404813885172,0.322003892825298,0.403443377689747,0.468618088420296,0.383780365956886,0.311102187329318,0.125213234034333,-0.229623144537333,-0.179903170203336,0.128797756997154,0.181328143577655,0.208275238436329,0.301567720389298,0.227561168470741,0.115728686127799,0.0627848472235653,0.0767430777335216,0.169188226477173,0.239061093801708,0.252082482812637,0.216139505500751,-0.0263496641341825,-0.0181743364918845,0.0720977815586048,0.143677743013201,0.233941716848825,0.262346271633584,0.220420456229524,0.160458346555372,0.0733843098376531,0.13956772582073,0.370438582113966,0.346488731927652,0.278750453489155,0.0806111592936716,-0.0410216127394705,-0.0483094190061313,-0.0453087246590752,-0.0562675843846709,-0.0118232316238706,0.0381612364684558,0.102604823988518,0.121099800190351],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(222,140,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2011-12\",\"legendgroup\":\"2011-12\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.148376010148328,0.189648519795434,0.263500611022738,0.270208496609157,0.230192967007303,0.171325161648849,0.15001537813968,0.0419526733708663,0.050006969650663,0.229632680324337,0.316667022156563,0.368166902107954,0.269145805467958,0.109779805102489,0.00598583388048613,-0.0214848270366403,-0.138957827546053,-0.242103993809292,-0.129997807091601,-0.0817436257835651,-0.0321249059543347,-0.0774731723709572,-0.189129121252838,-0.231455327688891,-0.20266472322395,-0.183549698818794,-0.198357604708349,-0.163308968358494,-0.167331473981854,-0.241348518872204,-0.120658319155411,0.15280429149062,0.333011656647215,0.385288143728589,0.294871684600411,0.192452440933776,0.00887579918459439,-0.263182607807934,-0.473481298462425,-0.360683983944885,-0.267207585948386,-0.155656544402417,0.0452182661746433,0.119143500460372,0.225600855031966,0.239442833764771,0.115760706196914,0.0614608874157596,0.0938301798838485,0.159734063778009,0.202005669600885,0.138560549142457,0.0212156102502251,0.118681273368587,0.239886280552168,0.145199988363085,-0.139030250573525,-0.191841730716743,-0.116580398004105,-0.119679293978393,-0.0577475740284173,-0.117804139654961,-0.298754628730144,-0.374536460548524,-0.285484358676787,-0.0518923929434748,0.0541097035874125,0.0325385546506314,-0.104820104085176,-0.216760659621214,-0.257390163702536,-0.17301329996764,-0.00450876592082966,0.268698156872384,0.268059737947696,0.155657905048388,-0.0619909108770192,-0.371046610253734,-0.417006572916437,-0.437409707567444,-0.382597925915983,-0.268539488456793,-0.201942964986764,-0.0915241164342476,-0.0748791279653921,-0.110417630580237,-0.128385307273646,-0.0156419155153122,-0.0611208312223415,-0.0990488817880458,0.0118479118871295,0.129006297325925,0.0825191021387745,-0.140327434670837,-0.376234582846064,-0.372995731298754,-0.411419233527092,-0.171814549452394,0.230041758700637,0.279863005432308,0.245452293016085,0.180094394214071,0.203278937699485,0.327904347213087,0.317668067311314,0.0792641805478551,-0.0974419830173409,-0.181512406058571,-0.283431871183743,-0.301307718042166,-0.199024582212571,-0.126371763162632,-0.0469413664805671,-0.00259956554272516,-0.0857666404963646,-0.0436095503752349,0.0782437171248369,0.0535684194532055,0.0565587572158845,0.0744401141011493,0.122395342070626,0.275127311098084,0.363499432028833,0.337280667618806,0.254875132254625,0.241331285974513,0.328952678022665,0.27779665999573,0.238821342482856,0.221835652859313,0.0757333410310574,-0.231855576541853,-0.261489950592222,-0.0966779112181446,0.0524132198744718,-0.0944024251291928,-0.280129754235637,-0.276614143907095,-0.178154462392186,-0.182393333364537,-0.396660535833266,-0.287201877694325,-0.148813863511825,-0.323829096142237,-0.35241208114538,-0.416962305672081,-0.366685592820439,-0.374693986962231,-0.271367454139376,-0.161654190909138,-0.0483641319529423,-0.057463002326186,0.011034141984507,-0.0570675030644865,-0.0158587178570935,0.101683588567775,-0.114496892488907,0.00215490146771198,0.298850718406883,0.381403899555606,0.380831323023578,0.300079034802877,0.202096040985148,0.0734654632392189,-0.10988858723004,-0.00614249873929563,0.149512974405949,0.244621378861593,0.184932357626224,0.0899401465779475,-0.0505825220085238,-0.0465769116978189,-0.129078548307012,-0.229077444611069,-0.246792448997859,-0.242233060028489,-0.215748568819024,-0.270441410821464,-0.293293928986794,-0.267163048221208,-0.320489019732482,-0.119123678271464,-0.275330184215267,-0.411988128297393,-0.268202500878354,-0.137897355310651,0.333776821787706,0.42312401228438,0.286957161161375,0.261297870471027,0.247939013848157,0.238449023304113,0.231591797052122,0.307235467130268,0.438517066280916,0.194790277566122,0.0554015487455146,0.0269865841969086,-0.0445918261137462,-0.101989520250177,0.102245285002104,0.171635539135268,0.345094212316807,0.278285308933497,0.344313056300129,0.315150075341971,0.320397881829954,0.180135763787341,0.243306346219829,0.236155128865327,0.165495985200059,0.122547460801462,0.109693984677006,0.037312322198311,0.0892453769233193,0.171339360678792,0.244335269226143,0.284190693404617,0.325567758330695,0.429993819716669,0.403079257074855,0.389573577188088,0.589695529804877,0.515462942306407,0.467659616284131,0.38830209225123,0.260774252433816,0.229793392163395,0.177221493559096,0.156985868009508,0.153170932113772,-0.0288398652987025,-0.0997556673648946,-0.112306736299711,0.0156919018206954,0.142273736310759,0.238372716784863,0.299843601770277,0.370649187278426,0.411035767229534,0.448727773205717,0.545643450449132,0.559351571217957,0.410583046406153,0.336439812182589,0.36414828459094,0.338677930677773,0.286214178289083,0.300566988401469,0.344884286683979,0.356950998404705,0.441201922919188,0.414867716400358,0.367617150829391,0.332325866973768,0.191275605413737,0.0931100439676211,-0.04766748476924,0.0634843683465159,0.239321451026422,0.225660374058804,0.212727811110263,0.138414082199284,0.0431794108745656,-0.111210515200518,0.068622641691917,0.393595101866501,0.384568353316997,0.361046908355313,0.374834880118361,0.315749516654083,0.281725677380362,0.33488600213512,0.24192016188243,0.190594212246501,0.158906705830501,0.238341032914171,0.271146838924655,0.265975527926656,0.306656665761437,0.384157028371785,0.343129522688063,0.259714855139458,0.239024158490268,0.162614724965489,0.117766310693053,0.184737146590116,0.244488168665802,0.271164025946145,0.16560361298981,0.118168080415116,0.160173401923142,0.127418630938426,0.216806475561642,0.259395406855351,0.335745912663458,0.302649394128975,0.232882148063394,0.191913927600543,0.0892547549545251,0.0600795085861278,0.151038792532871,0.206919013344333,0.239729723610782,0.210377489309643,0.169047287098107,0.169035225317764,0.342373705218606,0.349899511440421,0.331420709905227,0.467156976686266,0.45112696058299,0.468640760113896,0.47011799331208,0.451865937067481,0.380227856612196,0.354161668628242,0.286410734257902,0.307895888034385,0.26716334378942,0.275786195579031,0.206206738418586,0.156037039663678,0.02462393503988,0.0525606694884962,0.219913604492431,0.482760018373584,0.501418775351167,0.378829160149874,0.356904733418709,0.301183838632299,0.222796694344845,0.218955554957168,0.205371326480983,0.221292820306973,0.0828057114147766,-0.0740065981340396,0.00528607241556978,0.0224388991194228,-0.00389485703289096,-0.0636038732313167,-0.190166406943839,-0.307148865362107,-0.228964354505885,-0.133305979473684,-0.114423194434284,-0.16180792541276,-0.188108618379394,-0.246509834708425,-0.275690941961141,-0.265526337087064,-0.18634082186741,-0.133325618301993,-0.156513209119272,-0.206487190435498,-0.213546406558598,-0.108539777204512,0.0687503312998867,0.14517587459493,0.123163492791637,0.0857585358570252,0.10151230543491,0.105153875143638,0.0889052173063948,0.109785545144773],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(183,159,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2012-13\",\"legendgroup\":\"2012-13\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.20195705809084,0.268426050990456,0.351093102370128,0.42175325475356,0.397941885420997,0.366356049721549,0.252581341923395,0.235163865717714,0.0841143792239668,-0.0649478543953112,-0.199238946497265,-0.191179483703396,-0.242324083587589,-0.109545809768168,-0.0293656544377561,-0.133211539861551,-0.273070984385202,-0.348487902780134,-0.335850028274777,-0.249585601768136,-0.166849901079678,-0.101386359212993,-0.0426615171271292,-0.079949268128632,-0.226145757642932,-0.276089039304153,-0.305319614560699,-0.235503024589284,-0.191815650987551,-0.0623158579445686,0.07804276460722,0.0386618480100539,-0.113467974841929,-0.180146134717153,-0.0683617900460965,0.0375210137018213,0.0717645846586817,-0.105249805343214,-0.158574865327085,-0.0458008206195777,0.020349677152513,-0.0792754109811962,-0.127612008705564,-0.32940033726774,-0.336275610091304,-0.16827106237049,-0.0973071341700102,-0.115505897992848,0.0879788515534947,0.258374892998887,0.243719545671472,0.306388046120679,0.182444836084186,-0.0289490048160302,-0.0780317802265337,-0.0129082087528,0.0517970366290036,0.136185104861761,0.0666840450442592,-0.133820975285006,-0.285848038477215,-0.258931136561748,-0.17058281359008,0.1568715540798,0.250843341384771,0.244768507118967,0.257169611419146,0.235520162826362,0.204579861365532,0.154019587054229,0.0909655145854029,-0.00113178477728964,-0.0995561311320254,-0.0592828323300522,-0.028222691909276,-0.217232620535863,-0.30598675193895,-0.37567025376484,-0.353267993452056,-0.366639173181458,-0.232108988294373,-0.289073989283867,-0.270499846133821,-0.224597864539687,-0.217998749687451,-0.259273604581414,-0.350623623028615,-0.164014362074772,-0.0706672569119484,-0.100941762912969,-0.28096300899201,-0.25118047477112,-0.017452656972168,0.153852901239635,0.0662066014856378,-0.0949395227604615,-0.25209478203298,-0.0922751291287296,0.0972133752330943,0.221735994169638,0.0712840806302784,-0.179770135061113,-0.38052393471137,-0.331382956916562,-0.246159486043747,-0.108494429511173,0.0838529563694645,0.294111138089034,0.363624813120348,0.38400154254191,0.417052633500461,0.351081552984011,0.172307753743129,-0.0548322350307886,-0.154916964282819,-0.133904963413446,-0.193390895658373,-0.199597617748444,-0.190346608668036,-0.15608469105955,-0.196083626415399,-0.251188419305276,-0.407233494497922,-0.354477051262534,-0.277495504328737,-0.25383813944822,-0.295839771495388,-0.282569374919897,-0.0841097645490197,-0.0720464890680918,-0.000175160967456179,0.105784109506709,0.14626870175384,0.133667701911236,0.109297937205663,0.100422611647407,0.174586966156205,0.252161931878645,0.324543492859541,0.278840307252217,0.0715242688010299,-0.156817016761951,-0.232961071164311,-0.140792795193211,-0.0404313743578439,0.0187035981550617,0.125747256125836,0.0469709573818196,0.25624594336227,0.586949038807903,0.644989065154767,0.365000055580107,0.0284063221878392,-0.23854318832394,-0.338572786693545,0.115129550526404,0.400024777463577,0.0648928527023793,0.0585182422569887,-0.0299917177805347,-0.102628250300924,-0.125834736019196,0.0428127715070404,0.344083359972115,0.440113292231135,0.395612615753477,0.256891620713938,-0.0311759975583732,-0.16772933696065,-0.0824391981961787,-0.0885376057847717,-0.139868202910326,-0.0297026474505355,0.180508846930963,0.158322781407475,0.286107961454088,0.422532137341913,0.432469745899424,0.375180651069919,0.327802233486887,0.225095880782893,0.251707618540331,0.322934264105956,0.334295343691367,0.445077276044766,0.41994249781698,0.388832029472603,0.397437702042624,0.505351233340116,0.410925091106273,0.245200351733807,0.285833354559766,0.356805792707867,0.295456218694425,0.279357116443918,0.270955445338648,0.163287535533327,0.122362262619218,0.164837615305522,0.370331499831178,0.455442152874114,0.321574260821685,0.293132482879608,0.25902306485914,0.22657964985632,0.139660942964409,0.0655046214436946,0.0136310735297558,0.0304408038477078,0.0834848886645782,0.170984061408429,0.27932035834605,0.295312145040138,0.30334648412157,0.392373244746778,0.424505539419503,0.362068029624553,0.321578704568531,0.33529181490871,0.44882276936563,0.427516164865381,0.451929638825262,0.415151341754914,-0.293748971913992,-0.37352320084743,-0.074080410073257,0.117953468313372,0.207334980593005,0.295906231204866,0.257741466397262,0.250802841044011,0.297867587331647,0.37720578863286,0.331717608674149,0.345077202891302,0.353954794484398,0.347377654770175,0.344888523912086,0.322656238896458,0.328672807791469,0.363750766221484,0.379352482861795,0.314434274518059,0.135259954891984,0.0610256464820791,0.0573263648778563,0.147051596772671,0.247794947318544,0.275872975635516,0.305960217583716,0.366832524459578,0.363243930594175,0.381266360228189,0.440389796909921,0.443405842288615,0.461540763940408,0.437707963543411,0.443259434882987,0.450580080324133,0.392923788218454,0.34480816280136,0.332414354178409,0.340280855031986,0.325422039057906,0.29226812442603,0.286184382572583,0.212963969519254,0.225488426986083,0.286447463772134,0.316744015777664,0.345587156704248,0.337160996786914,0.300404541890084,0.320502923175809,0.311112424400945,0.261403437880884,0.319576538446096,0.371995576124258,0.39234784004249,0.375831144734209,0.398697107217862,0.248275568000825,0.388968971602717,0.430266684972214,0.459686506744838,0.32938595332006,0.240528715097205,0.374296584964465,0.480474389191191,0.614639442339141,0.547314771352455,0.408403393479145,0.306298304730196,0.207905441926927,0.215052073155118,0.246426290486344,0.214818831462056,0.201806660432874,0.240153433191266,0.33074324085751,0.254584280149225,0.13331581632784,0.324938667045767,0.399156450839734,0.327782803702556,0.28213435299207,0.272229641106408,0.415350560386515,0.289104113654738,0.128314106672074,-0.0654072919488857,-0.216411611371034,-0.233212268223215,-0.0648599000954631,0.186253729022395,0.239475732751516,0.308520743701009,0.263148295211505,0.248372708258423,0.22559235950215,0.220132089313114,0.24667962639339,0.215754961219731,0.197469740579493,0.167691134354625,0.171498916604934,0.194191243516477,0.159448426998072,0.284604947949686,0.318810464194034,0.249349449113931,0.212197633858109,0.166369923243492,0.130891324691575,0.0449636100076173,-0.0463567552835761,-0.0143431037499517,0.0947583510570383,0.338913882919494,0.48264166099835,0.475261062848936,0.426555855617668,0.430172810396599,0.40983305210188,0.399937781059021,0.286046908927299,0.298027707035854,0.292979039677872,0.288068695115836,0.172158350236701,-0.0247396141666918,-0.0830415444178513,-0.149774693092354,-0.196989707880159,-0.116862310427897,0.112359135189806,0.327346809291859,0.362896701188409,0.340866200866894,0.281996127213951,0.180956692418797,0.0741712820236922,0.189790234307303,0.233474574116725,0.218374208396125],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(124,174,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2013-14\",\"legendgroup\":\"2013-14\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.209110459976333,0.161690405941665,0.0104345566690263,-0.066788372758365,-0.0913572915118213,0.0620974195052891,0.173094414924953,0.116709324531528,0.00916437703991221,-0.0026205963238702,-0.0151986140095334,0.00408760652788018,0.0617436839516368,0.257311900697357,0.305179661337939,0.222333057206906,0.147320284351687,0.0251082213749597,-0.0884264114879326,-0.0611777145251145,0.00406820984548459,0.0897584934392256,0.137141177872201,0.153334271684515,0.0736981494682051,-0.126936047870946,-0.166420219261484,-0.0979296573529822,0.130230098617674,0.235044441733874,0.192067579481954,0.120697913457874,0.131972244880795,0.0708084350647921,0.125265376498769,0.204500368403045,0.214435320288839,0.182410901752612,0.0355948601176412,0.0351004220300148,-0.122734759846903,-0.262885402691402,-0.351475952190311,-0.413857916199605,-0.247396175278206,-0.0790786822596554,0.169299863621415,0.268619828856272,0.357113447870268,0.30706010247496,0.196068426006258,0.211547610892358,0.235333205434182,0.228736522028699,0.231468011304694,0.15930377993631,-0.0391165870503377,-0.276606092264475,-0.29143725255196,-0.268483579229666,-0.212624963476479,-0.170731700556143,-0.204394018983545,-0.257743204169882,-0.111967545471498,0.0285989366145156,0.0774904156896196,0.0624576725012298,0.0758469667687738,0.125467098500836,0.117217636431204,0.111667646191079,0.0990231122504636,0.0412841138913528,0.0212558293728081,-0.0747572983897566,-0.270475323919562,-0.338831274079218,-0.272659037164451,-0.250816351050747,-0.13998913129922,-0.117212261894754,-0.151918407102649,-0.193591170592976,-0.193427448781453,-0.173249740484107,-0.0950619392682234,0.0215662012148302,0.157593093328294,0.160672572795953,0.231426898204889,0.195363670975899,0.122349622198846,0.038815145105158,-0.0224894042236715,-0.140490841091363,-0.382536964332073,-0.371794411170924,-0.261606008153733,-0.247102601775837,-0.225709845368661,-0.233648131633831,-0.367413214882092,-0.426717306419265,-0.345284689980154,-0.194720332693081,-0.0880773847166799,-0.142637568213815,-0.186285752241928,-0.338955680257128,-0.435712350053532,-0.410789830875271,-0.15722792105097,0.14940622463942,0.226611061740527,0.116237279421537,-0.0274494540804277,-0.169938732869629,-0.270568052773916,-0.270420505062835,-0.201420225639703,-0.281054614074338,-0.304824736310509,-0.192142912331555,-0.0210362917831028,0.142452924517636,0.256361901302148,0.25324005487139,0.264816021873018,0.354865189633083,0.476201821036192,0.382676682560654,0.292382583781493,0.286572022571473,-0.00266168104323407,-0.298629844184341,-0.319790940978761,-0.324654811407052,-0.31340396748299,-0.316361182250885,-0.180936474211628,-0.0653465891076518,-0.195740509350031,-0.351673912343453,-0.335732833928857,-0.30861459329084,-0.354677623102987,-0.297216612691523,-0.144706748177524,0.0816799543949217,0.108587193576606,0.271936226374287,0.0950910279031549,0.00991845956284189,-0.232025488105555,-0.270014706017485,-0.0218693658520614,0.161430648071803,0.464900202941986,0.546128300046778,0.406661085880828,0.380140092388733,0.401457644874781,0.393002266673134,0.441528242758983,0.456982617702639,0.484062729966302,0.440538725513005,0.468923450305707,0.31292077795207,0.246820073542169,0.0671237588767724,-0.135421429462348,-0.36865933774306,-0.287403020611734,-0.0576998715963287,-0.204833225457784,0.141482674791432,0.32217268474129,0.392446704086264,0.236168094787539,-0.0405611568470333,-0.284689709395784,-0.130637307150218,0.155783088000289,0.297128764025976,0.189139757883305,0.142662933574583,0.212394995969022,0.281759246898414,0.368436569720353,0.598613153417854,0.578600655242659,0.69924327953673,0.736968863644708,0.649023816081386,0.394838878642151,0.383773606160203,0.44088327779354,0.617403695104417,0.0356797800760798,0.129451258771063,0.163008797329509,0.0729820715416483,0.0195272828285351,0.00416423872023569,0.0528361076348254,0.0815527547046175,0.15982777549538,0.312902868762179,0.381253490450572,0.328596022396996,0.359684353456758,0.301632975745352,0.264862892498541,0.209498566142855,0.120416142906922,-0.0852149314624225,-0.113143948331699,0.0526732641021032,0.310950047374097,0.454736944950374,0.420944434601655,0.354813821578595,0.313524004391532,0.295517614198849,0.315465873851965,0.37788065610671,0.383511584429655,0.395891892106218,0.346186696976055,0.326531584792547,0.43680986266264,0.422373760680836,0.247006246449132,0.0926620524444737,0.0479357914525943,0.0575774989745682,0.215521170771018,0.291699039033385,0.28887447003621,0.256389696495695,0.151843036911946,-0.0323463614103367,-0.0673303270169888,-0.0314536774184605,0.0355984673385022,0.132630246006981,0.232698617549749,0.258604849727875,0.300508357568478,0.313985550918673,0.264519028778618,0.190776829379795,0.167611648725331,0.32991023411461,0.535901782738546,0.464275148681423,0.453469230143308,0.469599449687071,0.415206760335338,0.317400379638999,0.239371264065917,0.197455116493181,0.342538478928353,0.405431453490277,0.414907946470714,0.417414147073222,0.269645146123531,0.229749542344792,0.214509840517404,0.185624943398775,0.168054197143137,0.108628634767777,0.0614570498783653,0.158369299390891,0.238522278109912,0.213131647122165,0.233245240091738,0.264946452345593,0.257619963647012,0.26873994327251,0.336324738764694,0.348207204800432,0.256121914728478,0.20595668154423,0.235501210553347,0.203817021524914,0.230700214997921,0.210415922759958,0.138650385939227,0.0801086693997408,0.103236995149509,0.285829536352622,0.346709172079491,0.262539553049892,0.269682331193087,0.229690640609842,0.216434116836926,0.307221051525191,0.303151877072602,0.293545865036583,0.260032490559471,0.348573363594467,0.290371463543837,0.215105508164794,0.220873305825481,0.222677813675869,0.279288399369277,0.256169482125323,0.245534821763713,0.279185850849481,0.283858198248831,0.239011770946774,0.0878937521071285,-0.000769410793293238,0.0888015225168021,0.0970977292802328,0.0358551415203578,0.125986829154339,0.23002916592378,0.248815397670939,0.306675209960002,0.380462315021842,0.342451253729343,0.306680160610479,0.139606938995615,-0.0442856874695444,-0.0658450583495269,-0.00844127794864189,0.139670730511259,0.389589303303079,0.371546808162719,0.289221119163771,0.222420532487513,0.141097991182454,0.106736484913351,0.024166012906408,-0.0199156931749065,0.147919631231516,0.140035096288812,0.158934941226289,0.146640254390012,0.0796798987721739,-0.11899464211349,-0.263967250611254,-0.156672983605478,0.0761856542082472,0.215184419776669,0.251578506020475,0.206961218754946,0.00641685499441113,-0.119064810164041,0.0530979129532231,0.129075266432586,0.132654098326317,0.110189732164218,-0.158110206450495,-0.246055176248193,-0.180019138690905,-0.102420672335777,-0.0307225256995615,0.0187020035009286,-0.0901214629005488,-0.214664793660655],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(0,186,56,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2014-15\",\"legendgroup\":\"2014-15\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[-0.224572495747871,-0.31481590765815,-0.336360686975513,-0.227074942080875,-0.207528146074491,-0.190823843771779,-0.016702897603663,0.106333503404364,0.051130720423287,0.0880521782461841,0.205673381866446,0.24375729916149,0.251101330174347,0.218490638256365,0.222847612953038,0.0893623492474172,0.00398253291269237,-0.233313670492183,-0.265407466290605,-0.125182873307052,0.0519361483427708,0.196216069497096,0.178755999129243,0.0961950574582058,0.0293869869826488,0.0909015809120016,0.134228229342163,0.162894542559795,0.197333244032135,0.230923245409363,0.22859048487508,0.201861290465052,0.254947730505894,0.298985892858294,0.268426560052572,0.236473816901413,0.256449734146017,0.297159809015942,0.320375899437845,0.267909965275467,0.259829280383938,0.210907130105476,0.147351143559137,0.0748464680509866,0.136408791749269,0.226849029233614,0.275915998826577,0.254257985233867,0.280433857334071,0.307923474842114,0.244115328510284,0.054156983619028,-0.289943897904954,-0.321958069090917,-0.187151130995844,-0.0509331024802642,0.166581599443722,0.230663452920735,0.176504021406521,0.0921005355200052,0.0835746037022111,0.0886876973970172,0.0673074800731205,0.0352257425655734,-0.100723515446754,-0.249559741081181,-0.295926096851146,-0.315788332388265,-0.370567222408965,-0.387782276309138,-0.327941657526024,-0.291081249868201,-0.162576479165838,-0.14813499317089,-0.274551960029788,-0.460933107962248,-0.437677236159583,-0.3299848408638,-0.081116669246001,0.317461128201487,0.298430806774258,0.271837866664123,0.224917191715714,0.0428939055974604,-0.0898482145424924,-0.014135736048509,0.123688208093541,0.12563037777784,-0.00632586957984786,-0.18226629136422,-0.245333997426188,-0.114886350903415,0.067683739038523,0.0962904720426572,0.0963972605785621,0.112261931542794,0.13893124146304,0.136113659747563,0.20537575907449,0.217904252530691,0.149732476510483,0.0792751720200461,-0.0801750025791231,-0.0569707290515885,-0.0432395890071223,0.078120175611303,0.0812873798951318,0.00616977468808814,0.0964598013142868,0.221219190186368,0.190746539944633,0.115305079138054,0.0764206415698968,0.0319491729775475,0.284666569534718,0.109357002287402,-0.0288785664430444,0.00344826908196436,-0.0855187318589733,0.0626912263979824,0.481702420035665,0.438326929399738,0.15861946404225,-0.044118511550599,-0.240034435518771,-0.311367326900433,-0.23324007796893,-0.283385199629938,-0.382028096136715,-0.362517948896699,-0.286912201859331,-0.240684874090241,-0.224957248384157,-0.108986536101524,-0.089016674285987,-0.0327158175009097,0.0470177933373838,-0.0243536727949614,-0.102962688042311,-0.177316127238074,-0.0985433792188013,0.0562054501893309,0.112170222313305,0.0400643474840851,-0.0296740395785644,-0.282770937666692,-0.310230678838333,-0.189571804298125,-0.0969719824157671,-0.13158719035233,-0.243867067897938,-0.246059912430329,-0.34340114836697,-0.280767528621054,-0.312855887210235,-0.354689001517645,-0.332439056232431,-0.302266233220623,-0.22742987286849,-0.241610963513292,-0.0698890648310909,0.215879315818257,0.369057311840229,0.264386431939378,0.219857814129841,0.154581314999482,0.0399608622657742,-0.014437780386419,-0.0755493664390937,-0.144623239088216,-0.0716142056502886,-0.111739235802716,0.0298677531274975,-0.101520446255265,0.000855966961729788,0.257102865708566,0.307716065902372,0.204204354497369,0.0535900826095123,-0.217764630532731,-0.298400923513959,-0.250775990278716,-0.111836775087888,0.123263255950319,0.276021751385696,0.0659156267796525,-0.139536881302097,-0.19823675682238,-0.192712139456784,-0.0540756926051407,-0.125707905321712,0.0246574554368927,0.0303137742486725,0.133672973001846,0.171896452770346,0.153073459182386,0.0729060537425204,-0.00407850470874782,0.214430817026792,0.376953362762464,0.30645956238662,0.0851757678181132,-0.0613976761498582,-0.179742909641158,-0.13563445582583,-0.0228290772164014,0.224653063353068,0.23035871070889,0.166529647251787,0.122271081183215,0.172922627090237,0.207509851948278,0.169742738506596,0.195538500587535,0.279655569622871,0.270107204173933,0.278953549902132,0.250207151834332,0.265452069642741,0.25669145725837,0.212529720424694,0.237576572211003,0.235753127188424,0.257714663726643,0.270024654298495,0.303407225941715,0.353747901889636,0.317108553505022,0.292813647272238,0.274891641917759,0.251185735386332,0.243462448934746,0.236920373762948,0.24714776696312,0.250711614551282,0.275050026499269,0.310695783825061,0.33299511939358,0.313771949570709,0.320482902176723,0.297597660655562,0.270020813470341,0.222950405206115,0.163887806569636,0.0500680804132213,-0.0519890924390524,-0.0449576808214092,0.0287496955368812,0.121677954018029,0.182814544026416,0.182712275968302,0.18530096881017,0.185002074011866,0.213988276021723,0.396501433868976,0.390989592140706,0.362766087803507,0.308257201024388,0.248972197699028,0.154282241877333,0.194193501348678,0.192535034368696,0.27118930336425,0.292540280699733,0.295623804323807,0.235790166176216,0.216324321311088,0.210142257211094,0.18080452780783,0.108608783651146,-0.0720452209658966,-0.0672911427598743,-0.0251486870016127,0.186519803606788,0.336764436811669,0.327606384688861,0.290625045242954,0.0771401921992341,0.0492615717744135,-0.0586213547662725,-0.183155597644329,-0.18457679250601,-0.0917407559717773,0.0703208965867371,0.24637759423628,0.334376740908051,0.280792660050023,0.336794903241418,0.451612276858805,0.364169107831297,0.267351929917963,0.186575383163824,0.115859953333892,0.189460601836406,0.255678065630097,0.263367166935668,0.22045975986363,0.0950245024643469,0.0799569033743971,0.112358949236591,0.163208365586037,0.275493462313586,0.471296855469775,0.26656895354029,0.207258621250895,0.220398336378944,0.29091867432544,0.239333531229366,0.172067079898168,0.0940819314190304,0.0996362637868523,0.0655318041061859,0.200095481133131,0.273515093691928,0.237305862768843,0.201258693772367,0.227219405980448,0.336261423305583,0.49418823650833,0.294968402848931,0.31186766425863,0.161479035111173,-0.0170269137590345,-0.134546641362545,-0.0287313502055512,0.141620048899362,0.109325554830391,0.131836164042467,0.189044841502034,0.271606983002231,0.386393861136614,0.503349019381402,0.522442303597056,0.455192504906369,0.348533138844,0.256080227146099,0.178564788768418,0.0984962638817835,0.252806765662093,0.313644733719164,0.34993238759078,0.362030398041109,0.384028952458821,0.309662733322919,0.230843302304271,0.159158744211489,0.154596752139435,0.224272055116983,0.323915440833982,0.399186901668703,0.528020790930141,0.402679937739965,0.316670862159893,0.231563648570597,0.18672117417971,0.152024285822574,0.0408334314273041,-0.0657049878423879,-0.248154298010764,-0.225140565978968,0.108309685549405,0.327864950196016,0.300948403756543,0.255795910260886,0.232229079289074,0.218124723458099],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(0,192,139,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2015-16\",\"legendgroup\":\"2015-16\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.143324699496529,-0.142963262065349,-0.267212736285094,-0.0270481957781939,0.278891440062637,0.364371421205507,0.356781816579444,0.345678521194338,0.304832392853137,0.166848070758253,0.0274072971715145,-0.0273844683216245,-0.0307771569274493,-0.0132366022594376,-0.0208610245066819,-0.0668398900024282,-0.00947033205726937,-0.0102944598283199,-0.0981730029061221,-0.217989476361574,-0.212214962238063,-0.195339077758894,-0.1684393192453,-0.180215883783946,-0.2098723602908,-0.176069956617117,-0.203874111870428,-0.218878195583245,-0.326373239448742,-0.330712649200218,-0.293059797857939,-0.227402171189781,-0.23884393596903,-0.188850827302966,0.0823360262163125,0.291013764981044,0.318877054873737,0.304089127267238,0.214702190512183,0.107214070711445,-0.0134011245283874,-0.064808417434143,-0.105173038893755,-0.0321284757451061,0.00723156180784952,0.135197779819867,0.136536185098463,0.0922764527847628,0.069871576363101,0.0601085836772899,0.114780625431736,0.141638357580479,0.0903652447419709,0.149589826314906,0.222234149516551,0.229501228137578,0.246584371306311,0.196198269682328,0.0906862756091573,0.0515770647539817,0.00204271908979032,-0.102084623215069,-0.16849036685455,-0.0887922301530349,0.00145368553845092,-0.0179425213958267,-0.0991899482927444,-0.224522365680248,-0.227942340048631,-0.220387877360145,-0.238216012505423,-0.259911473803111,-0.342679935341716,-0.386430216036995,-0.277574039248807,-0.0331641892267036,0.202340098996251,0.283288165778608,0.267513524193861,0.181914987723053,0.0947620607118354,0.0720006249900868,0.0923853760554874,0.0624111398870839,-0.0839643499320378,-0.168012318892434,-0.0824986811993528,0.131703405623942,0.247287150984572,0.203496656782974,0.0275789108921316,-0.173956265758901,-0.252074651756774,-0.2054462688734,-0.0705716456101182,0.0645237157778211,0.133626170443804,0.159129513556951,0.0551315672366884,-0.0612993375134932,-0.101302319001085,0.0598162088924448,0.165946680508346,0.157091048858543,0.17956299093504,0.0817428176205298,-0.0337176343620924,-0.0798640489857213,-0.137659847142439,-0.0418844971564191,0.120927896050631,0.182371268335589,0.110044717580444,0.0528239770801261,0.109132033601568,0.159663530804584,0.130031866494035,0.0888019699736521,0.0507766592806429,0.0454450609786412,-0.0148763712487416,-0.165274444343995,-0.0781581284881297,-0.124201899489868,-0.252706123736521,-0.271079477943588,-0.148291087627886,0.0133187402571155,-0.0733713636573666,0.139859914933979,0.260064703737313,0.0976914259741692,0.11876162372326,-0.0364828089854159,-0.0537223596243526,-0.234596070133231,-0.335944607780636,-0.23102374778206,-0.182472017989775,-0.0712451499800971,0.0384759321641402,-0.0188580226150499,-0.117177303429157,-0.0764143023361563,-0.0930039661685363,0.0252797405063778,0.265138684596463,0.272233404248032,0.213009167482634,0.129905889363153,0.168598953789899,0.245255577131864,0.25639408104417,0.188756600981749,0.207482019630497,0.19285189130709,0.179222699957902,0.200761742208932,0.311721350453479,0.242983622606133,0.262428767993568,0.276054429425325,0.246675227676996,0.223253016287537,0.0609060140077423,-0.0298595001884713,-0.0993900794727611,-0.0548710986683885,0.240552413191889,0.286478199326583,0.248357328115649,0.112167115411338,0.00506102275529926,-0.0743455940014769,0.00522272780167576,0.144766884344448,0.295824173469981,0.301508561496022,0.280785254609226,0.314182797155563,0.292792449666564,0.297098332220718,0.24052333227184,0.173145488689106,0.18590436045576,0.181912467509132,0.0804203404531858,-0.0403561789615845,-0.0517055029522207,-0.140111229956911,0.0798339453586024,0.2506106390718,0.226626552397373,0.1934882601119,0.136100760578132,-0.0469900777012285,-0.103080901037293,-0.0913447706347756,-0.19499332300718,-0.0612207109555044,-0.106629364757822,0.122335000968561,0.114016305913844,0.0805270098993651,0.0584772264027968,0.126735885911864,0.313312565985452,0.320610036145779,0.259139800026431,-0.0478681590077532,-0.415030211334963,-0.299863214226103,-0.0329490407611322,0.269972531943344,0.296436404159971,0.306873607950692,0.294944733421928,0.295916202148,0.366101384834339,0.327046811962131,0.218236609674039,0.148214869213653,0.179550103438105,0.254953775523121,0.320872553263017,0.283052433375675,0.2496917088886,0.231516356823132,0.272011679101915,0.296821921476167,0.353738560238445,0.337696490265299,0.293098035903498,0.28699720478965,0.247452367413799,0.223379800411671,0.169510714606352,0.122455959506161,0.0113955902554771,0.0313670990812207,0.152670405594631,0.162482968408,0.201912498529708,0.242967738882097,0.216220271384287,0.21724556950647,0.28192748722037,0.320023715917406,0.285450178323897,0.265258357816892,0.234531585404204,0.228312560257889,0.315803566983896,0.274276676161958,0.214174352780122,0.211737612648305,0.206173956602241,0.209570208134091,0.260948098621036,0.282205817086702,0.42377371040353,0.307752823629781,0.259962263181822,0.26660135083314,0.276391543097382,0.260940973962051,0.27944094595896,0.237962302748282,0.141486218418918,0.140966393209328,0.218307384430613,0.293721463450912,0.368222246465068,0.464260456036413,0.44461452056116,0.294956511240661,0.279423058364117,0.207675295734973,0.255856375279111,0.310954090701553,0.230079741810819,0.194666392711524,0.203756073483833,0.274650777059368,0.271273860052095,0.271659299919126,0.304479676316988,0.296733112556111,0.270084439804439,0.243844428082118,0.254264109833675,0.300160521056398,0.283528025677715,0.297773963131445,0.294241136357825,0.253407410787897,0.241470282172382,0.240955140860177,0.244501829758451,0.214379974033719,0.203113521295344,0.229052548609206,0.293831760712918,0.302222841344062,0.2864805383886,0.261391277017973,0.266832312654129,0.204498082250835,0.147887825940379,0.0981479828371462,0.0893496686927653,0.124434851677324,0.196570511880202,0.263612153631765,0.255705576321561,0.252832333724134,0.239911137454971,0.243076196825846,0.209774225638074,0.239979142882428,0.212351721125929,0.131941141170976,0.113506819664179,0.118102959265614,0.134411771555565,0.154697938662974,0.175805592112719,0.199273920227116,0.197235925381117,0.221579845861783,0.249409995063741,0.2163746745483,0.114823739710209,0.0390109885264164,0.048495370764981,0.0247135746533556,-0.00521012893285834,-0.0936597390549165,-0.194203040890742,-0.303156384533496,-0.311016044122001,-0.268803403987168,-0.052358988694167,0.087898365353815,0.0806040651494859,0.0645754318081454,0.10386043092481,0.0988888418515744,0.0190780039617688,-0.10717513898386,-0.150260705174677,-0.120300612284403,-0.0725763024103538,0.0900361016412456,0.178748136104314,0.15461605915502,0.0819995197460251,0.0413939157053029,-0.057167278802786,-0.0445978167179594,0.0883461790197073,0.119718756864155,0.102925497663273,0.132616445545233,0.183478461481268],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(0,191,196,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2016-17\",\"legendgroup\":\"2016-17\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.154941974441103,0.084392552756143,0.107402251951727,0.0775606498838341,0.0622346038572764,0.0466621883758105,0.059755019579748,0.0837515181019796,0.143211018537146,0.150717774315014,0.19390746259312,0.192990258658332,0.168011193150736,0.0943693995361901,0.128671492775763,0.247341286533257,0.274312963888113,0.287045243736068,0.257076998391453,0.196091792354485,0.0917128058495858,0.0200447367511513,-0.00549234620418303,0.0388124159745453,0.0547774464036884,-0.0102375160795336,-0.171360652318995,-0.171715963405596,-0.186852191496581,-0.167177769376129,-0.186896536173267,-0.12683739236181,0.0261434363119007,0.252226679690237,0.183962425004525,0.0883496419664972,-0.017007421307368,-0.0143317632321574,0.0275594460933383,0.09783593849795,0.137733841023445,0.169309724763173,0.137578109737776,0.0599404741354606,0.0426687225737399,0.125991958895183,0.210720705433601,0.231272485091556,0.175026255515495,0.15854975985536,0.172883608604662,0.00512377875488926,-0.0716637452143834,-0.091102343699729,0.0280919538629118,0.0852238653512917,-0.0650035877059582,-0.222273573126397,-0.297008615441565,-0.307811147577179,-0.276138810289647,-0.301452205470929,-0.281640508628192,-0.282383875513561,-0.154292640142838,-0.0296677835338871,0.0170634083007069,0.0699107449215781,0.0303401341340169,0.143159724484384,0.33287537512353,0.31641207451319,0.227705690506553,0.255647336826705,0.237563466485978,0.218709144257938,0.20606839255781,0.173917137492473,0.132479471490136,-0.0163599788442826,-0.135619894563281,-0.166691945005822,-0.0384327127277247,0.127190127962037,0.14991368611378,0.165918103135216,0.150398543889257,0.169328346889155,0.183358283511932,0.226592116992941,0.152575734800272,0.0581989725926271,0.0538831928098852,-0.0745377888395888,-0.135285005618685,-0.0574097213805443,-0.117525726615652,-0.228947782192678,-0.215696451387772,-0.186182915829523,0.0406425936251379,0.240993328844751,0.263968408765054,0.271551313130428,0.26089753430672,0.212385561759221,0.212260836758457,0.222878575139711,0.205882322080239,0.116528771351085,-0.0127304317968512,-0.0833869786417784,-0.0638795821972099,-0.0603545145862862,-0.0597086096299784,-0.108129319784693,-0.179359836728703,-0.149161689370719,-0.125139403737954,-0.0808955902358301,-0.10443535318463,-0.226434126825623,-0.31439473942559,-0.361067626176243,-0.314506310092327,-0.313441398580607,-0.143356044476951,0.12047124499923,0.179367585724643,0.164693826208332,0.171322521467662,0.121502067145566,0.0237954499797897,-0.014675836270048,0.007261644401566,-0.175492892232939,-0.323464967316885,-0.104067192165368,0.197415667304806,0.249733838560219,0.277177973361986,0.209147658648798,0.156221288107087,0.162421547387522,0.229349543854171,0.227035436602413,0.267769735055762,0.267439713383309,0.22169386063415,0.21486882573732,0.192360504932529,0.022762622386601,0.0823041448903808,-0.0950975841920733,-0.0418537065832161,-0.0728865797980343,-0.0183479321825431,0.226428212723394,0.57420459299996,0.48803803519687,0.396953216345506,0.279972752975342,0.175895809860501,0.027478221787296,-0.0882178367370504,-0.169124397136322,-0.2313719662688,-0.278654508797457,-0.188860260043296,-0.0534100124458814,-0.0692287799279512,-0.0732724515948102,-0.058259171786761,-0.0947156071796342,-0.152053282701922,-0.262958371178299,-0.395608257869026,-0.416104711156841,-0.398126519642807,-0.402951291217383,-0.305986745722318,-0.277621595571304,-0.232755802597117,-0.0799534360355314,-0.0110517973434688,0.0247143287652948,-0.048120601454057,-0.0509021810704933,0.158564013440513,0.387474806022011,0.451419322722933,0.342652988120105,0.332443815691603,0.29491597123905,0.272477980175598,0.271137334859137,0.270024175286567,0.270743202493496,0.234047736544572,0.180422700565382,0.147909895292478,0.155480374907891,0.217929154587118,0.25665912285851,0.223437811767773,0.0777677755202553,0.131788342766634,-0.14875268390901,0.0209000519861455,0.22440690052819,0.168229322834925,0.291619239747759,0.483407773494393,0.359119569572409,0.319668544100771,0.200714156480855,0.140957143777411,0.288366093027608,0.318430888270468,0.382573839946507,0.40578384198718,0.354806192010572,0.29090330368827,0.264718026903524,0.237891475357724,0.236247012495258,0.298851727525118,0.240686554186858,0.192127496957501,0.217989223808581,0.270375270655171,0.278032511755738,0.270354034583301,0.263722962060822,0.243026900764182,0.267982730246378,0.233834239424026,0.169154058396983,0.103536204536855,0.131408439267978,0.198775922802931,0.27442358958885,0.274794696057877,0.241833967664182,0.210476819213046,0.204070005892799,0.233041679884652,0.313299047039249,0.29756520405814,0.260224093376228,0.238677883884784,0.202740657302543,0.13555789278849,0.169359237677798,0.298306395851837,0.281188932127829,0.287781634768859,0.276624329667118,0.316482640123071,0.464278934163614,0.421413276854612,0.381908185052884,0.405655660126022,0.370921924935139,0.307464739465288,0.217849318162719,0.175228587634249,0.25605592928745,0.306085480432249,0.249566052764831,0.265377442629666,0.32109685019201,0.264222768646881,0.223027425115103,0.185343839310217,0.124872693278099,0.0213627639665778,0.0386588676587752,0.159419451713177,0.308317232194904,0.270276205900314,0.27396697444945,0.231520285666516,0.124551947811293,-0.0399692598447464,-0.184632493885021,-0.0896405430409312,0.158773062193054,0.265517050170041,0.324189639856174,0.365904309420971,0.328804966027027,0.229716062150942,0.174780058907504,0.181011997848009,0.223415643162184,0.306151144847,0.311620287691017,0.284810233760973,0.261292332006139,0.270120183412051,0.252021678703004,0.293410554694587,0.34311203606702,0.31507830783713,0.32328850402713,0.347237213188102,0.31222278672713,0.283911547081546,0.253545322702827,0.288699054958053,0.342702543232563,0.274872455831934,0.201608912657535,0.21739830273727,0.209846544782698,0.181426565241646,0.175724246196726,0.157283894634416,0.172466815576715,0.161853982892439,0.146871395241598,0.061121711606034,-0.0593384359542315,0.00952764103316124,0.0159470019129843,-0.00436952524317146,-0.0215835680552979,-0.0584122734003744,-0.0535412510670055,-0.0938735862557489,-0.151171715288663,-0.0886791051077501,0.0436389930736059,0.106849942175594,0.111618155696057,0.117637088633239,0.114649595181981,0.073336689330899,-0.112280694692704,-0.230377335540096,0.00998508227081273,0.148818119341447,0.188983969359781,0.124732583414716,0.0211448709654363,0.0368614720745297,0.220050335224763,0.204499349018641,0.15829983776912,0.0310421597291108,-0.129002125269113,-0.138538779469058,-0.0108327639579288,0.134223132569338,0.0654438124517076,-0.107453148803949,-0.140597716825506,-0.0376758937700773,0.0214808349809274,0.0872498824998118,0.125604516571908,0.0843128669045202,0.076705188591971,0.0226834959729332],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(0,180,240,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2017-18\",\"legendgroup\":\"2017-18\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[-0.126134337758254,-0.175791259212555,-0.194066331446175,-0.178540991571698,-0.165854675550721,-0.0770189410833075,0.0852109697499197,0.153691988666713,0.0802178888977373,0.0908011221682332,0.120186539562543,0.122177659831687,0.169744727511278,0.211233772961669,0.173092743258261,0.0879795936231988,-0.0740192693898705,-0.0159640973963282,0.0655531845048789,0.0974384470046918,0.134516287321305,0.275671591465273,0.312184240795215,0.282522955755312,0.28200461406989,0.25283933133082,0.183110635893884,0.132015493794355,0.176342716133586,0.247320127418529,0.30978858745732,0.380536828021877,0.291328371133494,0.202799475768842,-0.0395374603788658,-0.234217792577619,-0.175849097874327,-0.0966732235732466,-0.0466884722232219,-0.090751221129229,-0.208560806938637,-0.331729207180454,-0.359383408417504,-0.237636151533786,-0.189220603520346,-0.25832933256027,-0.293029615371343,-0.349736614113191,-0.211947912582287,-0.0657758928241314,-0.135400311007203,-0.305168241908859,-0.321078241191298,-0.214502755233981,-0.0686478512932472,0.0756554071247811,-0.0133306387080965,-0.199443453602895,-0.26390526469137,-0.206495188590796,-0.033091717001054,0.114073714389,0.222299797640806,0.252601299938346,0.123877500970371,-0.0170362081354682,-0.0728415144412786,-0.117482430271015,-0.118609536119807,-0.0978044972140513,-0.0112302281181691,0.0842788998210495,0.209394598816719,0.260288366670335,0.210375624382568,0.144720621281575,0.0966433677665432,0.0438636702737078,-0.0344326315661705,0.00926965469656623,0.0106435518127692,-0.151913551932945,-0.357971706106378,-0.375685952152503,-0.389787811602634,-0.368826940930656,-0.363002677183366,-0.368428245528396,-0.346393317426383,-0.33813368864952,-0.317677759075966,-0.159630157932462,-0.225579469988343,-0.383494779073018,-0.450887584135359,-0.406226927600886,-0.143444342545474,0.325139752071888,0.376654453179215,0.306199082227116,0.128738434794647,-0.0665767299964137,-0.220694926811149,-0.239416786310356,-0.327128455356747,-0.345663504250242,-0.204018690369177,-0.120410131220952,-0.216723814147787,-0.175331240563411,-0.0791233057813621,-0.0721962153549432,-0.25050614292925,-0.278671663898384,0.0893902312071116,0.43581285795239,0.379791457222127,0.366798390322066,0.407412493555454,0.392344592166306,0.324361435770632,0.363791095920475,0.283176748276008,0.323426229394906,0.207874600778793,0.0953222179282617,0.150090802506748,0.0465384142925302,-0.0200768522974976,-0.159418171902823,-0.171520093056721,-0.131982516934329,-0.0677314796693928,-0.0220005374948723,0.230796635499421,0.289577026839009,0.291475960569761,0.255328616403231,0.188028463736854,0.0884709924076334,0.0409163762921815,0.133691863601556,0.186512387644169,0.174649593252163,0.149901614652592,0.076892482908041,-0.107840399913295,-0.26427072888454,-0.104502406227667,-0.0447705736101433,-0.195097156578878,-0.331976531351336,-0.360454437466016,-0.345677202615507,-0.292310088887892,-0.24158851389829,-0.172870770894409,-0.0611672124680797,0.0088570393898334,0.212679851438967,0.357779701915274,0.555742283128427,0.362582488249002,0.27274225515542,0.183966194445277,0.0276649723388821,-0.122383857060224,0.0720246479335835,0.3036142270965,0.330628573739563,0.190512326739223,0.134729037070271,0.256453258250739,0.224927006138656,0.355911754546583,0.23969626109244,0.208362901207723,0.34438195345285,0.395201637718198,0.358617489966887,0.299030605275854,0.262842666284804,0.262726721729579,0.289216367371206,0.310556158738457,0.305851941315516,0.29081483652712,0.285228069408585,0.124689410495317,0.104850152636018,0.218801169795816,0.249806562790148,0.21662605784713,0.181575782840172,0.130272561931726,0.0516803684922877,0.0432071381766771,0.0612493087433897,0.167373961296395,0.0153971684308322,-0.0918475685661795,-0.00690612405382387,0.114669560051312,0.0824959874015822,0.201538803276319,0.221736851531385,0.130254850020613,0.168976975097564,-0.0256930218715808,0.0788945949225782,-0.0655854514134045,0.0192205339340884,0.0122994682270442,0.411839212842253,0.436036850290235,0.40625670334979,0.365577285699134,0.288520021022692,0.281565837229528,0.255061095520013,0.191773395710788,0.219111444329456,0.214417779084649,0.206841184599586,0.384106308787292,0.367003001836582,0.289974952508007,0.212212238979497,0.182400470558542,0.229131972180342,0.276433181640953,0.325948107994568,0.331934830431513,0.258589231771371,0.207144450823302,0.212896763050213,0.132325116341597,0.0814406565465302,0.132132815950781,0.209005576252417,0.296642422634758,0.228970956389878,0.182878386226485,0.209250506705671,0.23891834989285,0.289627485201881,0.22512704736194,0.19960217340035,0.159476023000536,0.158938773176826,0.165469840541489,0.226728703920885,0.376962189692903,0.381643222372565,0.321116678385101,0.405919407464404,0.372544350916804,0.303761659761058,0.256995772908581,0.271938270111142,0.283644496154176,0.297137006795715,0.287559363892196,0.253769869389111,0.260151250612201,0.256015670870977,0.182607084547765,0.117422334553944,0.0984161036381801,0.0745891214302633,0.0766359293574335,0.100770289274682,0.16308615350092,0.238458714589389,0.429154659930975,0.401002810788551,0.348685736125153,0.364549314155558,0.392798542606603,0.36078801379234,0.344318615069448,0.324222498432028,0.248485863836995,0.210357172669633,0.140493184539293,0.107487921357021,0.143736993495095,0.139992654782941,0.146364368896674,0.16536807461702,0.140564325647485,0.113521552409989,0.175916444733144,0.228900039143304,0.270023824912878,0.272897395241762,0.23965004180021,0.260012883116511,0.327514876284729,0.330297178010896,0.33115263859427,0.311033262197848,0.285292235119549,0.236512789648302,0.215122017944923,0.188075205079472,0.222170279770002,0.278701444390833,0.295744978887644,0.297392653248875,0.251662810869955,0.219402534619593,0.176197459483953,0.0625677355746486,0.0786861774609077,0.212400324403022,0.279342171791822,0.318541639060178,0.276174241783802,0.251290739104099,0.262891235607583,0.242380694036081,0.254084472275638,0.27954574348246,0.281205135031505,0.295402411284724,0.273176992267002,0.286976139459365,0.235941601372111,0.203468290185543,0.214955501932283,0.224849685487459,0.233366914896454,0.238106716769923,0.268419255363665,0.273174610433188,0.330767496274807,0.302365189127947,0.302445185145534,0.281265558034388,0.234576313888011,0.148324961267623,-0.0044791578703321,-0.102562302570819,-0.02655819358109,0.0935492636773813,0.147009004823431,0.238191998799338,0.287280675142926,0.260965734105419,0.221548944687684,0.168046644769749,0.159326309763921,0.224870498570249,0.334322952173933,0.263805865108706,0.101300372736881,0.0349924364707902,0.112481408240752,0.162466632060179,0.129140643846841,0.19751562801337,0.187892097455701,0.156609269596182,0.172542354033651],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(97,156,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2018-19\",\"legendgroup\":\"2018-19\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.165466182393686,0.161980716551097,0.160201976643044,0.0683505328874703,-0.0432445824899949,-0.193320088223763,-0.315880173491877,-0.187100941633511,-0.051068439507954,0.0272036863230773,0.206179718190381,0.294686599466613,0.288341354706278,0.231465478309345,0.130496511765848,0.0889605057313542,0.0943705209205285,0.0358049175020414,0.0566326876439544,0.172677245937646,0.214909240912105,0.241192596191711,0.249476647324014,0.196953607940575,0.166005720355576,0.219446970188386,0.208338299315145,0.170892617019007,0.0926213057966554,-0.00237617496475929,-0.023569019710412,0.101520368631742,0.249123012539705,0.297367278586928,0.305079088780641,0.211615517091157,0.0727333671107007,-0.105596619927892,-0.285408971697322,-0.251043031976079,-0.311620584627243,-0.27677025229989,-0.232847808659489,-0.270113610228516,-0.362794492996884,-0.34543722848551,-0.26821186454476,-0.247694310781913,-0.301656706760783,-0.228658098257579,-0.0983529351517346,0.104349048168863,0.287624491952101,0.247087544578126,0.166515249299715,0.0858052590334665,-0.00629169602819831,-0.052567074288249,0.0242598307868141,0.104817871557225,0.0913275389238607,0.0613449930949025,0.00361625144854939,-0.0291259374896714,-0.0482502986197275,-0.0828025069170938,-0.0923479743276579,-0.0581533120981797,-0.0379517858760281,-0.27187355921583,-0.147887295759953,-0.163405999637175,-0.1396956980238,-0.191297032466088,-0.27566248475913,-0.235765782838295,-0.142454659205965,-0.063486244894747,-0.166894645636804,-0.184458205266855,-0.148494660398773,-0.0773436203107541,0.101546313349844,0.189482070400531,0.128844200680414,-0.0349372922422449,-0.172280136507456,-0.214154932748427,-0.140592403982731,-0.0772313654713263,-0.0724488787481052,-0.239283678930572,-0.364332182042157,-0.320601832712382,-0.240488563585244,-0.279322856860183,-0.255910162339626,-0.252888085692636,-0.217538996193097,-0.0687825302513862,0.162568958361431,0.240842536073957,0.0913691219274923,0.0296912320671736,-0.304818430940829,-0.376833420441922,-0.29443561334609,-0.22955722500161,-0.126879749447739,0.117384448055255,0.251718210059896,0.181498331809002,0.1216244216612,0.0680468228905608,0.0161726496551094,-0.169053379476417,-0.371558984758037,-0.192834151130508,0.0352356307719089,0.142545406573589,0.201173680102403,0.0537285316159594,-0.133304027058477,-0.039105461429179,-0.0261794652797112,0.0899722595788143,0.171054422321034,0.0449226251959568,-0.0695614772745321,-0.103611802247377,-0.0473730417876371,0.0567541060122889,0.101041743952436,0.135648826452282,0.137227433238618,0.218739351284311,0.162684698214326,-0.0364345237670317,-0.251008693234796,-0.315321775910505,-0.291565503317478,-0.26457932442094,-0.235188144119784,-0.140183286073529,-0.185745241168922,-0.207887782445415,-0.138476140812287,-0.168811086129807,-0.17248187296355,-0.314503845818035,-0.370831915823766,-0.201298659831831,-0.111428095498775,-0.0840395598505453,-0.0566427927316315,-0.00401561202211929,-0.132267115813641,-0.139221049681744,-0.221885481723142,-0.18645745512677,-0.235926268842793,-0.276172095832085,-0.342111794833254,-0.338171807190099,-0.265743744784106,-0.305790362620604,-0.307731887331939,-0.323905677837867,-0.28385763130475,0.0693888453714904,-0.0866276296568506,-0.181749356321018,-0.203454332495407,-0.326021318206295,-0.338376193133283,-0.475777925546768,-0.434966236215654,-0.319714415036003,-0.20865728384817,-0.33102153151947,-0.23163217005064,-0.0769985271778204,-0.0493326843555863,0.0830518508594576,-0.00280786289552274,-0.221175642889331,-0.340663433328075,-0.276423062265493,-0.0179672528994076,-0.152450365102172,-0.160811971262541,-0.12855835048138,0.00974193504439238,0.368591919869157,0.353303994826689,0.286063617316561,0.206507130237203,0.140554040342663,0.216854968328408,0.33448390852568,0.330716984698989,0.277828821804777,0.284294069038704,0.272582402624329,0.257114211844035,0.256277594155256,0.259550255217657,0.25800113559862,0.234927264154714,0.221623641192841,0.221373956726399,0.262348022456339,0.24364038519534,0.189330614508698,0.178514602772918,0.185541377666907,0.0233686571180169,-0.0244608272934341,0.0729051959908928,0.11793377722733,0.197831429441364,0.222008212671653,0.231031903284911,0.197929894044784,0.0580974408702772,-0.0400794187262676,0.128008979535466,0.30081482288904,0.258830453689977,0.17060523461583,0.0400314125692814,-0.19465281212668,-0.16722042003039,-0.0379386206184892,0.12183251814517,0.230973209332013,0.259000011052752,0.295697576281259,0.307516365455666,0.352763146555716,0.260716154662699,0.179199632637175,0.161487328053334,0.094523191810683,0.150416384581567,0.277490099571738,0.271502299395182,0.285822470319312,0.375102384710368,0.33303011805643,0.262929595608788,0.208586215754192,0.186906314059634,0.247610837975449,0.24517836702649,0.234102738203199,0.248861858147042,0.266420722811086,0.228046749900728,0.261667858084279,0.258109537664083,0.260038251466359,0.229928788469606,0.26425428653652,0.245344860011408,0.207758456053357,0.184144688129356,0.153964223114261,0.11934877532344,0.109591728035691,0.130614479915669,0.183159967138272,0.255194601149539,0.244252203557586,0.201689280021154,0.145515911293757,0.206649333677866,0.295794987917475,0.325357330629764,0.3288301619792,0.230692027567527,0.263412956945116,0.27148752616249,0.29180387468507,0.295588163716953,0.293987069645834,0.29631370617441,0.212543681701431,0.153727678906226,0.16575232116777,0.252582829258146,0.319514897039847,0.359242041511467,0.340520647435516,0.301288154804551,0.243783398012924,0.163136785264551,0.19670576611681,0.239271573030972,0.230421000314626,0.245308102283676,0.226079173608832,0.238163337928892,0.248040484671029,0.21868568131766,0.225143436435582,0.244067162847432,0.281207145949556,0.223126417560836,0.240693535854754,0.236990978458917,0.254758259974232,0.293371120461057,0.274728566926654,0.22293613801596,0.158233885920959,0.16806539140296,0.255617138994174,0.235759531961606,0.220221398547768,0.162537483011471,0.127464715848682,0.126043462774824,0.162074507683458,0.187994458239965,0.196023428491813,0.278533675559142,0.325257044896136,0.304469381711201,0.212668460872549,0.109913794748333,0.144129976409967,0.222606955953284,0.223655050046019,0.261693914722497,0.376613099364759,0.321843404053659,0.270990556317824,0.239694378949582,0.1919804072768,0.0860079452298309,-0.0433223810454772,-0.178727484963909,-0.0432778781294213,0.0338726691108078,0.0471322503305625,-0.0679613109674515,-0.102309195703053,0.00771742675467928,-0.085535652560915,-0.122370358151335,-0.159231051702497,-0.289672772051303,-0.318865492505807,-0.319659160431423,-0.201772208230324,-0.157592708933432,-0.0697515301495222,0.0750540929182101,0.207564381681203,0.317763400273993,0.322691553103244,0.369076926441476,0.389971111927275,0.358777409044119,0.30544000506941],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(199,124,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2019-20\",\"legendgroup\":\"2019-20\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.274859959314776,0.219893634927467,0.229676258672923,0.224884617734994,0.200126300100999,0.225571990554102,0.287280146915799,0.339602880298669,0.287023631706274,0.275403235572744,0.178942276027543,0.178574860637197,0.272623942393437,0.318203175081682,0.324780565278847,0.298024501787288,0.231615162426132,0.180621463034606,0.144856111153231,0.166731094530253,0.136535736414937,0.160944008753294,0.0603883170016401,-0.0218839667729774,-0.110504546373539,-0.146746960665937,-0.0486668042402452,0.109006999830051,0.194884723161455,0.26192499301037,0.234422367845278,0.242224858621702,0.280642032973387,0.257329540269036,0.227090845726303,0.227404437400624,0.201747500006928,0.17607456323462,0.168815056067619,0.164415419502414,0.164953137890157,0.213551247441568,0.282494746242201,0.294302674540647,0.286775298867041,0.259825764263265,0.263096664711877,0.192790319763858,0.0572640779784312,-0.111690524449993,-0.154724698562343,-0.149312670292781,-0.0892298250740783,-0.116019199959584,-0.249503470326489,-0.288404410104635,-0.129786229267071,-0.0740382849189313,-0.177564932434216,-0.318557256718628,-0.376836869104694,-0.283319765717805,-0.145148656887724,0.162199476989475,0.262978587532369,0.117045599563664,-0.156418346248574,-0.305432001436393,-0.242938425563037,0.0467052883647492,0.234362826678475,0.217971054960487,0.0844252558788008,-0.0989077624001477,-0.257819795335551,-0.21797520250623,-0.0403038212436228,0.0332252194781357,0.120577564646988,0.237386695514998,0.272592211044689,0.28826920277674,0.263069135760039,0.235202432798948,0.0548234714103844,-0.137801868886763,-0.115153928806226,0.0917182145815161,0.241006626620046,0.193015450159886,0.0657273498007491,-0.00722057588525506,0.032527164314189,0.0909161579925733,0.141574116987479,0.112317531730146,-0.0731257843504213,-0.146850913398589,-0.210471085718682,-0.171167479269092,-0.0448749605575167,0.176013102807864,0.292279422338339,0.260808855707183,0.0456368360576341,-0.140665658277605,-0.245523665901316,-0.252574321579913,-0.206448259737056,-0.0658064644148752,0.0613580274939154,-0.0465315356871016,-0.262415346318227,-0.197522130455277,-0.170991857356839,-0.290569328975926,-0.251300245693543,-0.0521576453404615,0.0959037481987223,0.0157437342427083,-0.19679345841647,-0.287586135358177,-0.193739637729847,-0.0909847805198072,-0.146331905210557,-0.327496837332082,-0.313463848041608,-0.245989104299069,-0.271309535942712,-0.249702861544073,-0.123813716643335,-0.00341432047845383,0.25538246498779,0.297369661717342,0.365418493285729,0.413112129917352,0.393079077578853,0.345902590614774,0.345765715439466,0.166428009335527,0.160287035112884,0.212865972514357,0.328624015464213,0.305476203721839,0.326474397091048,0.257066940967916,0.223299737500973,0.111071395471975,0.117611912590622,0.137440169248385,0.39251702655037,0.421494746612586,0.370914825929917,0.337277631827946,0.244054194110392,0.0922328754576092,-0.0212551282768217,-0.0671397924118813,0.172916273206721,-0.0780869346810066,-0.0990335617300261,-0.00587865789556336,0.179319156868954,0.205260124722821,0.179791807932759,0.179662610420534,0.0727113681051853,-0.0744530691663405,-0.0545130379095364,0.136851153474023,0.402605641639333,0.442371692010846,0.342514261298074,0.228134741969903,0.0157032616025737,0.0849966999947837,0.0740915224646296,0.339252492546298,0.367782751123153,0.388376574819836,0.26988591932936,0.313380410553003,0.441028163572742,0.31797796455914,0.342295441844785,0.23894705974944,0.217313368702477,0.0274205160759235,-0.116056626038884,0.0240263322731159,0.156327007235799,0.221338090955091,0.279497543157599,0.273468831331026,0.266205481388683,0.202748704899527,0.164345707470541,0.170723084218001,0.157858785134126,0.137141963143659,0.127824947329351,0.144171738936944,0.182908323774843,0.0790936189436313,-0.122448884268722,-0.120872541540824,-0.065378126349338,0.055069877000726,0.336301994725628,0.377061288396109,0.383129703962313,0.429266359106068,0.463904450469326,0.40601378934867,0.368536101413284,0.297605561519331,0.309859924304301,0.257536022004545,0.15209711487394,0.0478598297489476,0.0136790807727135,-0.0936234260458387,-0.162011935641337,-0.0684332140496752,-0.0317899121919583,0.283426725724567,0.307664257497455,0.262595834032429,0.310528450242413,0.312383968018241,0.306238962560905,0.19965361963783,0.192149266546822,0.193385597356329,0.285392011687793,0.367750663084708,0.388405187898104,0.29525385594446,0.328036939436431,0.209978981880382,0.134614249784827,0.221009886005879,0.314221026783777,0.353063879320568,0.337529165189027,0.280489851849895,0.220730974576172,0.0605226184068086,-0.0061353892005296,0.0535002290420949,0.229509570907765,0.291360289081355,0.24495724682135,0.182002264719612,0.151525454909264,0.182273710993456,0.211343226114016,0.270402907821666,0.362202487102845,0.393319706236825,0.402024624982295,0.352256248338836,0.327219732367204,0.31299010300629,0.283907367418859,0.243436919228668,0.246599712866797,0.246316541723078,0.272976208209183,0.210727907286891,0.255463954540641,0.312262092487885,0.288296254304135,0.277301128200738,0.215021007823197,0.165302549267955,0.11889741274276,0.167705380137397,0.27746344882956,0.253444671311487,0.215552285082914,0.139093447063495,0.118713565799938,0.106454186254714,0.162562773942703,0.173714475532257,0.159465701558257,0.0380358315605629,0.0288057413723831,-0.0196123890973089,0.0115502917029834,0.142420084682836,0.166796333124207,0.156777964046393,0.212398950541523,0.211902416214171,0.157158041409305,0.0984476120720982,0.156062543826884,0.270867934974038,0.340931477570513,0.361550832839647,0.268001786692779,0.217187469025081,0.157916265013021,0.0976117809775242,0.195680909602115,0.305213536956214,0.321905064575091,0.297026294615269,0.18283507139737,0.16583483719945,0.177565206766822,0.245981215300285,0.220773489798855,0.238285423683537,0.25761996883673,0.211658741593203,0.0646923294294543,-0.166662878381289,7.08068248305866e-05,0.115181341769553,0.0687844462437625,0.10909294445464,0.120185493954378,-0.0930944896990291,-0.224291957981333,-0.0984780932247852,0.172681136441431,0.158927342452211,0.172410686175713,0.131069702115414,null,null,-0.0186585273366212,0.00739798100541308,0.0572946827195613,0.0405176351574714,0.151277032122543,0.190844417582389,0.223413741648296,0.286347556751174,0.296957686863383,0.286506349090746,0.291531521634129,0.330083488280804,0.357849524893131,0.320717026195008,0.299141162609396,0.325034862169242,0.296247472200531,0.250390806055128,0.232097602448997,0.302850868864158,0.335155870409206,0.29249300208193,0.232188106759049,0.088246663223723,0.0923797236286724,0.1112192917057,0.153254885155042,0.153504244459415,0.10098008052481,0.101900319364445,0.0535819045761161],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(245,100,227,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2020-21\",\"legendgroup\":\"2020-21\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"visible\":\"legendonly\"},{\"x\":[-62114601600,-62114515200,-62114428800,-62114342400,-62114256000,-62114169600,-62114083200,-62113996800,-62113910400,-62113824000,-62113737600,-62113651200,-62113564800,-62113478400,-62113392000,-62113305600,-62113219200,-62113132800,-62113046400,-62112960000,-62112873600,-62112787200,-62112700800,-62112614400,-62112528000,-62112441600,-62112355200,-62112268800,-62112182400,-62112096000,-62112009600,-62111923200,-62111836800,-62111750400,-62111664000,-62111577600,-62111491200,-62111404800,-62111318400,-62111232000,-62111145600,-62111059200,-62110972800,-62110886400,-62110800000,-62110713600,-62110627200,-62110540800,-62110454400,-62110368000,-62110281600,-62110195200,-62110108800,-62110022400,-62109936000,-62109849600,-62109763200,-62109676800,-62109590400,-62109504000,-62109417600,-62109331200,-62109244800,-62109158400,-62109072000,-62108985600,-62108899200,-62108812800,-62108726400,-62108640000,-62108553600,-62108467200,-62108380800,-62108294400,-62108208000,-62108121600,-62108035200,-62107948800,-62107862400,-62107776000,-62107689600,-62107603200,-62107516800,-62107430400,-62107344000,-62107257600,-62107171200,-62107084800,-62106998400,-62106912000,-62106825600,-62106739200,-62106652800,-62106566400,-62106480000,-62106393600,-62106307200,-62106220800,-62106134400,-62106048000,-62105961600,-62105875200,-62105788800,-62105702400,-62105616000,-62105529600,-62105443200,-62105356800,-62105270400,-62105184000,-62105097600,-62105011200,-62104924800,-62104838400,-62104752000,-62104665600,-62104579200,-62104492800,-62104406400,-62104320000,-62104233600,-62104147200,-62104060800,-62103974400,-62103888000,-62103801600,-62103715200,-62103628800,-62103542400,-62103456000,-62103369600,-62103283200,-62103196800,-62103110400,-62103024000,-62102937600,-62102851200,-62102764800,-62102678400,-62102592000,-62102505600,-62102419200,-62102332800,-62102246400,-62102160000,-62102073600,-62101987200,-62101900800,-62101814400,-62101728000,-62101641600,-62101555200,-62101468800,-62101382400,-62101296000,-62101209600,-62101123200,-62101036800,-62100950400,-62100864000,-62100777600,-62100691200,-62100604800,-62100518400,-62100432000,-62100345600,-62100259200,-62100172800,-62100086400,-62100000000,-62099913600,-62099827200,-62099740800,-62099654400,-62099568000,-62099481600,-62099395200,-62099308800,-62099222400,-62099136000,-62099049600,-62098963200,-62098876800,-62098790400,-62098704000,-62098617600,-62098531200,-62098444800,-62098358400,-62098272000,-62098185600,-62098099200,-62098012800,-62097926400,-62097840000,-62097753600,-62097667200,-62097580800,-62097494400,-62097408000,-62097321600,-62097235200,-62097148800,-62097062400,-62096976000,-62096889600,-62096803200,-62096716800,-62096630400,-62096544000,-62096457600,-62096371200,-62096284800,-62096198400,-62096112000,-62096025600,-62095939200,-62095852800,-62095766400,-62095680000,-62095593600,-62095507200,-62095420800,-62095334400,-62095248000,-62095161600,-62095075200,-62094988800,-62094902400,-62094816000,-62094729600,-62094643200,-62094556800,-62094470400,-62094384000,-62094297600,-62094211200,-62094124800,-62094038400,-62093952000,-62093865600,-62093779200,-62093692800,-62093606400,-62093520000,-62093433600,-62093347200,-62093260800,-62093174400,-62093088000,-62093001600,-62092915200,-62092828800,-62092742400,-62092656000,-62092569600,-62092483200,-62092396800,-62092310400,-62092224000,-62092137600,-62092051200,-62091964800,-62091878400,-62091792000,-62091705600,-62091619200,-62091532800,-62091446400,-62091360000,-62091273600,-62091187200,-62091100800,-62091014400,-62090928000,-62090841600,-62090755200,-62090668800,-62090582400,-62090496000,-62090409600,-62090323200,-62090236800,-62090150400,-62090064000,-62089977600,-62089891200,-62089804800,-62089718400,-62089632000,-62089545600,-62089459200,-62089372800,-62089286400,-62089200000,-62089113600,-62089027200,-62088940800,-62088854400,-62088768000,-62088681600,-62088595200,-62088508800,-62088422400,-62088336000,-62088249600,-62088163200,-62088076800,-62087990400,-62087904000,-62087817600,-62087731200,-62087644800,-62087558400,-62087472000,-62087385600,-62087299200,-62087212800,-62087126400,-62087040000,-62086953600,-62086867200,-62086780800,-62086694400,-62086608000,-62086521600,-62086435200,-62086348800,-62086262400,-62086176000,-62086089600,-62086003200,-62085916800,-62085830400,-62085744000,-62085657600,-62085571200,-62085484800,-62085398400,-62085312000,-62085225600,-62085139200,-62085052800,-62084966400,-62084880000,-62084793600,-62084707200,-62084620800,-62084534400,-62084448000,-62084361600,-62084275200,-62084188800,-62084102400,-62084016000,-62083929600,-62083843200,-62083756800,-62083670400,-62083584000,-62083497600,-62083411200,-62083324800,-62083238400,-62083152000],\"y\":[0.234190142177298,0.318158743438763,0.276889329262536,0.253192943139183,0.22324630144575,0.202069961811381,0.347609407741443,0.436607049497478,0.377284898277099,0.338467825402442,0.247838836507654,0.14179842315991,0.0657252846235869,-0.0107432866467249,0.0246746494256235,0.162074832854154,0.180391259081945,0.17752071052363,0.257881454574415,0.247199063788897,0.188214073072274,0.235242595531485,0.273578836367062,0.219891872308367,0.194453855543313,0.159142461479057,0.103207639135123,0.183896964715538,0.171149463245529,0.0594481433994634,-0.132943120192703,-0.442930614681537,-0.430888720198174,-0.345500453607584,-0.246845001941324,-0.166712236615616,-0.0322413549201171,0.0184897194265878,0.0560616150368649,0.0851065896150871,0.0440598091455322,-0.106673596513067,-0.281859300210797,-0.311415358118948,-0.291030010053549,-0.223877702911797,-0.225008928715757,-0.196982710023317,-0.185665707036558,-0.302804681301063,-0.402447304787418,-0.346118672170092,-0.295640333161999,-0.12889858650964,-0.074961868357622,-0.121753444757296,-0.130970390451648,-0.072093221992823,-0.131762418769884,-0.164912966443647,-0.124302289079017,0.000593415545002786,0.184335780241161,0.350238283072105,0.292780191517576,0.221864626939039,0.171172775137175,0.0704567070363951,-0.0811596130863911,-0.202421933442298,-0.299444769188787,-0.33364413372306,-0.356528777450804,-0.200177718491873,0.0639176504117175,0.079997657921881,0.00470790610848617,0.0528436788509331,0.183887888120689,0.273486763924642,0.183728634036554,0.019852430089676,-0.227736773888607,-0.335311032400376,-0.20712145346666,-0.150035850564962,-0.21357649885448,-0.260738391966448,-0.355088795423347,-0.313165371286331,-0.229147272743682,-0.185920780366396,-0.179644739049295,-0.130152373383855,0.0201441638152939,0.165308168427021,0.151199418763827,0.192596384423444,0.0208861526967226,-0.181079970487671,-0.323436053150511,-0.283373395253905,-0.211762476739047,-0.0589021898178411,0.170009046080734,0.183048920566073,0.12001398223915,0.0934070717583473,0.135674572662289,0.196930258078628,0.18693332711148,0.11026836190026,-0.0713430844905899,-0.188355325608484,-0.253401821885928,-0.231986853823999,-0.202323437449477,-0.175943030262924,-0.113417549976911,-0.36506879432636,0.0590363303239891,0.422642058510279,0.234419112831496,0.0543764931560742,-0.0597248377261445,-0.0480071798849006,-0.143503484436083,-0.319391914157887,-0.238706151959258,0.0190465657489312,0.139216626302519,0.0543366983183758,-0.0744734267981748,0.0769538121546966,0.268388657472077,0.280001466437245,0.103462748799046,-0.0825643946967985,-0.117764853494248,-0.0891080959600662,0.0404330111957723,0.222866084101353,0.320121720137795,0.340853869861883,0.276329273879601,0.183373729616256,0.0323896900016963,-0.120363126513111,-0.153563760891986,0.0604534328374029,0.42233707929541,0.406560081284578,0.271118747506733,0.121601187268015,-0.0473257272795108,-0.0757510946961838,-0.112163968128649,0.206999814457764,0.474248377548596,0.364919813779243,0.31532624661769,0.142882876844251,-0.0551382593250541,-0.222089734951915,-0.00747707191442514,0.249661488043852,0.316736141982737,0.284166958817944,0.240452205720958,0.191265150086723,0.138657481035812,0.133627627462793,0.186242269855885,0.251029037389439,0.246970750058812,0.203482077498341,0.147349652836826,0.0670011552416969,-0.0758396506001396,-0.110196736476172,-0.145843948501842,-0.165658040285045,-0.209154164331069,-0.297819574621396,-0.296355703504215,-0.287191405931333,-0.277174312936897,-0.33250974379484,-0.282827310793876,-0.179711409201016,-0.167020924670644,-0.10741430180981,0.0149313566853895,0.344008606632579,0.408966384850976,0.338992765157435,0.314850055251383,0.28455516114309,0.319517043725427,0.334749915058003,0.301505494187298,0.284959973002327,0.254208297462589,0.199698113853322,0.0791243571677746,0.0990808180712627,0.235459019056809,0.191782492211769,0.0510572108106534,-0.136575169500346,-0.140743340028067,-0.0780818363848098,-0.139635592023545,-0.0493038525324616,0.136755486889363,0.312529462278684,0.251865693957882,0.200634564688402,0.224663106572958,0.267429791893267,0.338432155845249,0.317440859176648,0.243735561324175,0.241552092577496,0.322043800527427,0.315490004009893,0.308681656472432,0.258570394686032,0.164607918167518,0.219723791728522,0.251895658108582,0.320186756012628,0.242882941654793,0.121220075275743,0.304800722003289,0.272845884474481,0.223698327801472,0.232860559569733,0.352053631588376,0.301096194600785,0.359216708393134,0.330068081922551,0.273041929719108,0.245486343748194,0.229522786081869,0.247750042670306,0.214129772358452,0.225245534662282,0.226551235462166,0.216143234865472,0.198038198007391,0.132040777679047,0.302548964069487,0.310251064558934,0.113611814247499,-0.0790509490569031,-0.191534691353993,-0.114990252782947,-0.0368144160728339,0.0191640078404969,0.132926021860663,0.220397769282757,0.334943689974724,0.336289858998974,0.288240809568296,0.230763099374039,0.173011034154712,0.184191768408537,0.21158725173387,0.150401767722052,-0.0104751333107304,-0.163558952397011,-0.209916211537164,-0.104003660759999,0.0344541423979681,0.15435713584736,0.187616037118003,0.206861555282296,0.140798817621001,0.133871055354701,0.237488754435318,0.317743789023992,0.301851473055918,0.270036882002679,0.250377495569308,0.191617281336283,0.244194681046724,0.314645817388361,0.339994506632375,0.331915998361148,0.346920196872813,0.34877995191796,0.314128621634831,0.324813763434407,0.349179301150475,0.385742470631488,0.33013007444669,0.313227505257369,0.392882509186572,0.418250104704529,0.423445028620026,0.370099809032146,0.319723485836502,0.273620996016229,0.318961199605614,0.329243893196565,0.353142211152519,0.315218727428143,0.221529551041731,0.126683788697083,0.0301199738898032,0.0574548072173608,0.161184663934916,0.174288784223902,0.0869213058599461,-0.0130433695588265,0.188309509760677,0.182641760306523,0.194285942479626,0.27834946823791,0.322814339715667,0.262524096291311,0.260778578988564,0.238947407494076,0.155854778297975,0.0795430399699303,0.178806886651733,0.229444876083444,0.30389497127402,0.334628224826837,0.30214319326863,0.264166426880826,0.266609462617038,0.293557853114927,0.304707644549654,0.29618490789014,0.292911711507655,0.197810647477454,0.0382430175876047,-0.196733223320918,-0.108089377450591,0.0819097326887415,0.267656496163648,0.257257639020715,0.206748380039887,0.20272894112171,0.189559290881654,0.199049247829116,0.196130134860626,0.0964019093888769,-0.0133371105129556,0.115668386352825,0.0866839892215262,0.0890306861919049,0.14601477837917,0.217710264322368,0.211555995121669,0.220506274790697,0.316565434600655,0.338578557583044,0.352267191643789,0.319198210669952,0.323497484313772,0.270274694709638,0.339297840291008],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.64566929133858,\"color\":\"rgba(255,100,176,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"2021-22\",\"legendgroup\":\"2021-22\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-62116174080,-62081579520],\"y\":[0,0],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":28.08800332088,\"r\":8.63428808634288,\"b\":47.4885844748858,\"l\":64.7571606475716},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.2685761726858},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-62116174080,-62081579520],\"tickmode\":\"array\",\"ticktext\":[\"Sep\",\"Oct\",\"Nov\",\"Dec\",\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sep\"],\"tickvals\":[-62114601600,-62112009600,-62109331200,-62106739200,-62104060800,-62101382400,-62098963200,-62096284800,-62093692800,-62091014400,-62088422400,-62085744000,-62083065600],\"categoryorder\":\"array\",\"categoryarray\":[\"Sep\",\"Oct\",\"Nov\",\"Dec\",\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sep\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":4.31714404317144,\"tickwidth\":0.784935280576626,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":13.8148609381486},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.784935280576626,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Date\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.2685761726858}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.536415265006341,0.797606203104282],\"tickmode\":\"array\",\"ticktext\":[\"-0.50\",\"-0.25\",\"0.00\",\"0.25\",\"0.50\",\"0.75\"],\"tickvals\":[-0.5,-0.25,0,0.25,0.5,0.75],\"categoryorder\":\"array\",\"categoryarray\":[\"-0.50\",\"-0.25\",\"0.00\",\"0.25\",\"0.50\",\"0.75\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":4.31714404317144,\"tickwidth\":0.784935280576626,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":13.8148609381486},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.784935280576626,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Northward current velocity (m/s)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.2685761726858}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":0.784935280576626,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":2.23335719398712,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":13.8148609381486},\"title\":{\"text\":\"Year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.2685761726858}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"42cc2ef04d76\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"scatter\"},\"42cc4cee6a11\":{\"intercept\":{},\"slope\":{}}},\"cur_data\":\"42cc2ef04d76\",\"visdat\":{\"42cc2ef04d76\":[\"function (y) \",\"x\"],\"42cc4cee6a11\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nInteractive plot of daily mean northward current velocity for September through August 2010-11 to 2021-22 (double click years to toggle display of all years).\n:::\n:::\n\n\nThis plot allows us to see what is happening both in individual years and overall, across all the years. \n\nOverall we see the trend that we have seen in @fig-ts where the current is predominantly to the north (positive value), and less variable, in (roughly) April through July with southward currents becoming more frequent and strong in August and peaking in (roughly) September through March.  \n\nZooming in to our approximate coral spawning season of October through January, we can see that there are often periods of predominant southward currents, however when these periods occur is highly variable between years.\n\n\n# Exploring wind & current\n\nSince we are interested in the surface current (i.e. we have data for northward current at 0.5 m depth), it seems reasonable to suspect that the wind may be a key driving force behind the current direction and velocity. Let's examine this suspicion with by looking at the relationship between the mean northward wind and current speeds. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create a wide format dataset (seperate columns for mean current and wind)\nmeanWindCurr <- data %>% \n  select(aggregated_date_time, variable, mean) %>% # remove unneeded variables\n  pivot_wider(names_from = variable, values_from = mean) %>% \n  mutate(year = aggregated_date_time %>% year())\n\n# Compute Pearson's correlation coefficient for the northward daily mean current and windspeed\nr = cor.test(meanWindCurr$wspeed_v, meanWindCurr$v, method = \"pearson\")\n\n# Dual timeseries plot of windspeed and current\nlabs <- c(\"Northward current velocity (m/s)\", \"Northward wind speed (m/s)\")\nnames(labs) <- c(\"v\", \"wspeed_v\") \ndata %>%\n  ggplot(aes(x = aggregated_date_time, y = mean)) + # and plot the daily mean\n  geom_line(alpha=0.7) + # specify a line graph of the mean\n  geom_hline(yintercept = 0, color = \"red\", linewidth = 0.5) + # add a line a y=0\n  geom_vline(xintercept = 2011:2022, color = \"red\") + \n  scale_x_datetime(date_breaks = \"1 year\", date_labels = \"%Y\")+ # show only years on x-axis\n  theme_bw(base_size = 14) + \n  theme(panel.grid.major.x = element_line(color = \"black\", linewidth = 0.5, linetype = \"dotted\"),\n        panel.grid.minor.x = element_line(color = \"grey\", linewidth = 0.5, linetype = \"dotted\"),  \n        panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank()) + \n  labs(x = \"Year\", y = \"Daily mean\") + \n  facet_wrap(~variable, nrow = 2, scales= \"free_y\", labeller = labeller(variable = labs))\n```\n\n::: {.cell-output-display}\n![Time series of daily mean northward current and wind velocities for September 2010 to September 2022.](time_series_plot_r_files/figure-html/fig-windCurrLine-1.png){#fig-windCurrLine fig-align='center' width=85%}\n:::\n:::\n\n\nIn @fig-windCurrLine we can see that there appears to be a reasonably close relationship between the daily mean northward wind speed and current velocity. This is supported by a Pearson's correlation coefficient of $r=$ 0.79. We can better visualise this relationship on the scatterplot in @fig-windCurrScatter. \n\nFrom this data alone we cannot conclude that wind is a driver of current, as it may just be a confounding variable. However, we have at least found a reasonably strong positive relationship between northward windspeed and current.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scatter plot of daily mean wind and current\nmeanWindCurr %>% \n  ggplot(aes(x = wspeed_v, y = v)) +\n  geom_point(alpha = 0.2, size = 2) + \n  geom_hline(yintercept = 0, colour = \"grey\") + \n  geom_vline(xintercept = 0, colour = \"grey\") + \n  theme_bw(base_size=14) + \n  labs(x = \"Northward wind speed (m/s)\", y = \"Northward current velocity (m/s)\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of daily mean northward wind and current velocities for September 2010 to September 2022.](time_series_plot_r_files/figure-html/fig-windCurrScatter-1.png){#fig-windCurrScatter fig-align='center' width=75%}\n:::\n:::\n\n\n\n# Conclusions & limitations\n\nWhile it would be nice to draw some conclusions from our analyses about the possibility of northern coral larvae migrating into the southern GBR, the reality is that we can't. Coral larve travel on complex paths and predicting these paths is an active and highly sophisticated area of research (find out more [here](https://www.aims.gov.au/research-topics/monitoring-and-discovery/connectivity); see a real approach to answering this question [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6802068/#:~:text=3.1.%20Biophysical%20models)). Unfortunately, this question is just too complicated for any real insights to be gained from data for only a single site. But, at the very least, we did make some nice graphs!\n\nWe also saw that there are indeed periods of southward currents at our site, and these southward currents are most prevalent between the months of (roughly) October through February, and are particularly uncommon between April through June. We have shown that there is a positive relationship between the northward windspeed and northward current for our site.",
    "supporting": [
      "time_series_plot_r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../../site_libs/htmlwidgets-1.6.1/htmlwidgets.js\"></script>\r\n<script src=\"../../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../../../site_libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/leaflet-1.3.1/leaflet.js\"></script>\r\n<link href=\"../../../site_libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/proj4-2.6.2/proj4.min.js\"></script>\r\n<script src=\"../../../site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\r\n<link href=\"../../../site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/leaflet-binding-2.1.1/leaflet.js\"></script>\r\n<script src=\"../../../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\r\n<script src=\"../../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<link href=\"../../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n<link href=\"../../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}