<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Accessing eReefs data from the AIMS server – eReefs tutorials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<link href="../../../../images/logo.png" rel="icon" type="image/png">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-99fa6729ad23987aafeada22b1565191.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-96eb28dfcb1a9f9f854aabaf44231fb4.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-dd6d2b9046317290f37c5b7801da76c6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../site_libs/bootstrap/bootstrap-dark-521a8ba0ec993f179c3d33aa6a439ef7.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-sm " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../images/navbar_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title"><em>eReefs</em> tutorials</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.r-project.org/"> 
<span class="menu-text"><i class="fa-brands fa-r-project" aria-label="r-project"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.python.org/"> 
<span class="menu-text"><i class="fa-brands fa-python" aria-label="python"></i> python</span></a>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">   </span>
    </span>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/open-AIMS/ereefs-tutorials"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivating-problem" id="toc-motivating-problem" class="nav-link active" data-scroll-target="#motivating-problem">Motivating problem</a></li>
  <li><a href="#navigating-the-ereefs-server" id="toc-navigating-the-ereefs-server" class="nav-link" data-scroll-target="#navigating-the-ereefs-server">Navigating the eReefs server</a></li>
  <li><a href="#r-packages" id="toc-r-packages" class="nav-link" data-scroll-target="#r-packages">R packages</a></li>
  <li><a href="#connect-to-a-file-on-the-server" id="toc-connect-to-a-file-on-the-server" class="nav-link" data-scroll-target="#connect-to-a-file-on-the-server">Connect to a file on the server</a></li>
  <li><a href="#print-a-file-summary" id="toc-print-a-file-summary" class="nav-link" data-scroll-target="#print-a-file-summary">Print a file summary</a></li>
  <li><a href="#extract-data" id="toc-extract-data" class="nav-link" data-scroll-target="#extract-data">Extract data</a></li>
  <li><a href="#close-file-connection" id="toc-close-file-connection" class="nav-link" data-scroll-target="#close-file-connection">Close file connection</a></li>
  <li><a href="#save-the-data" id="toc-save-the-data" class="nav-link" data-scroll-target="#save-the-data">Save the data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Accessing eReefs data from the AIMS server</h1>
<p class="subtitle lead">Basic access with OPeNDAP <i class="fa-brands fa-r-project" aria-label="r-project"></i></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="tutorial-description">
<p>Learn the basics of extracting eReefs data from the AIMS server with OPeNDAP in <i class="fa-brands fa-r-project" aria-label="r-project"></i>.</p>
</div>
<p>In this tutorial we will look at how to access eReefs data directly from the <a href="https://thredds.ereefs.aims.gov.au/thredds/catalog/catalog.html">AIMS THREDDS server</a> in R.</p>
<p>This server hosts aggregated eReefs model data in netCDF file format and offers access to the data files via OPeNDAP, HTTP Server, and Web Map Service (WMS). While we could download the data files manually via the HTTPServer link, this approach is cumbersome when downloading multiple files, given their large size. Thankfully, OPeNDAP provides a way to access the data files over the internet and extract only the data we want.</p>
<p>For example, say we want the daily mean surface temperature at a single location for the last 30 days. If we were to download the 30 individual daily aggregated netCDF files, with each file ~ 350 Mb, this would require us to download over 10 Gb of data just to get 300 numbers. The vast majority of this data would be irrelevant to our needs as the netCDF files contain data for a range of variables, at a range of depths, for many, many locations. However, with OPeNDAP, we can extract the daily mean values directly from the server without downloading any unneeded data.</p>
<section id="motivating-problem" class="level2">
<h2 class="anchored" data-anchor-id="motivating-problem">Motivating problem</h2>
<p>We will extract the daily mean water temperature for the 10th of December 2022 at 1.5 m depth across the entire scope of the eReefs model. We will then save and plot this data. This example will introduce the basics of how to connect to files on the server and extract the data we want.</p>
</section>
<section id="navigating-the-ereefs-server" class="level2">
<h2 class="anchored" data-anchor-id="navigating-the-ereefs-server">Navigating the eReefs server</h2>
<p><em>ADD: Info about the folder and file naming on the AIMS THREDDS Server.</em></p>
</section>
<section id="r-packages" class="level2">
<h2 class="anchored" data-anchor-id="r-packages">R packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RNetCDF) <span class="co"># working with netcdf files (incl. via OPeNDAP)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster) <span class="co"># creating and manipuling rasters</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>While the <code>ncdf4</code> package is commonly used to work with NetCDF files in R, it does not offer compatibility with OPeNDAP for Windows (only Mac and Linux). For this reason we will use the <code>RNetCDF</code> package which offers similar functionality and Windows compatibility with OPeNDAP. Note that if you are using Mac or Linux and wish to use <code>ncdf4</code>, the functions used herein have obvious analogues; for example <code>ncdf4::nc_open()</code> vs.&nbsp;<code>RNetCDF::open.nc()</code>.</p>
</div>
</div>
</div>
</section>
<section id="connect-to-a-file-on-the-server" class="level2">
<h2 class="anchored" data-anchor-id="connect-to-a-file-on-the-server">Connect to a file on the server</h2>
<p>First we need to find the right NetCDF file on the server. The available eReefs data NetCDF files are listed in the <a href="https://thredds.ereefs.aims.gov.au/thredds/catalog/catalog.html">AIMS THREDDS Server catalogue</a>. We will navigate to the eReefs 4 km Hydrodynamic Model daily aggregated data for the month of December 2022 and copy the OPeNDAP data URL.</p>
<p><img src="images/server_navigation.gif" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-overflow-wrap code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>input_file <span class="ot">&lt;-</span> <span class="st">"https://thredds.ereefs.aims.gov.au/thredds/dodsC/ereefs/gbr4_v2/daily-monthly/EREEFS_AIMS-CSIRO_gbr4_v2_hydro_daily-monthly-2022-12.nc"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then open a connection to this file using the <code>RNetCDF::open.nc</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dailyAggDec22.nc <span class="ot">&lt;-</span> <span class="fu">open.nc</span>(input_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>If you wish to download NetCDF files from the server you can click the HTTPServer link instead of OPeNDAP. The file can then be loaded into R by specifying the path: <code>open.nc("&lt;path to downloaded file&gt;")</code>.</p>
</div>
</div>
</div>
</section>
<section id="print-a-file-summary" class="level2">
<h2 class="anchored" data-anchor-id="print-a-file-summary">Print a file summary</h2>
<p>If we wish to investigate the structure of the file we have connected to, including what variables and dimensions are available, we can print a summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>summary <span class="ot">&lt;-</span> <span class="fu">print.nc</span>(dailyAggDec22.nc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<details>
<summary>
<code>summary</code>
</summary>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>netcdf classic {
dimensions:
    time = UNLIMITED ; // (31 currently)
    k = 17 ;
    latitude = 723 ;
    longitude = 491 ;
variables:
    NC_FLOAT mean_cur(longitude, latitude, k, time) ;
        NC_CHAR mean_cur:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/LCEWMP01/" ;
        NC_CHAR mean_cur:coordinates = "time zc latitude longitude" ;
        NC_CHAR mean_cur:units = "ms-1" ;
        NC_CHAR mean_cur:short_name = "mean_cur" ;
        NC_CHAR mean_cur:aggregation = "mean_speed" ;
        NC_CHAR mean_cur:standard_name = "mean_current_speed" ;
        NC_CHAR mean_cur:long_name = "mean_current_speed" ;
        NC_INT mean_cur:_ChunkSizes = 1, 1, 133, 491 ;
    NC_FLOAT salt(longitude, latitude, k, time) ;
        NC_CHAR salt:qudt__unit = "http://qudt.org/vocab/unit/PSU" ;
        NC_CHAR salt:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/PSLTMP01/" ;
        NC_CHAR salt:coordinates = "time zc latitude longitude" ;
        NC_CHAR salt:short_name = "salt" ;
        NC_CHAR salt:aggregation = "Daily" ;
        NC_CHAR salt:units = "PSU" ;
        NC_CHAR salt:long_name = "Salinity" ;
        NC_INT salt:_ChunkSizes = 1, 1, 133, 491 ;
    NC_FLOAT temp(longitude, latitude, k, time) ;
        NC_CHAR temp:puv__parameter = "https://vocab.nerc.ac.uk/collection/P01/current/TEMPMP01/" ;
        NC_CHAR temp:coordinates = "time zc latitude longitude" ;
        NC_CHAR temp:short_name = "temp" ;
        NC_CHAR temp:aggregation = "Daily" ;
        NC_CHAR temp:units = "degrees C" ;
        NC_CHAR temp:long_name = "Temperature" ;
        NC_INT temp:_ChunkSizes = 1, 1, 133, 491 ;
    NC_FLOAT u(longitude, latitude, k, time) ;
        NC_CHAR u:vector_components = "u v" ;
        NC_CHAR u:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/LCEWMP01/" ;
        NC_CHAR u:coordinates = "time zc latitude longitude" ;
        NC_CHAR u:short_name = "u" ;
        NC_CHAR u:standard_name = "eastward_sea_water_velocity" ;
        NC_CHAR u:vector_name = "Currents" ;
        NC_CHAR u:aggregation = "Daily" ;
        NC_CHAR u:units = "ms-1" ;
        NC_CHAR u:long_name = "Eastward current" ;
        NC_INT u:_ChunkSizes = 1, 1, 133, 491 ;
    NC_FLOAT v(longitude, latitude, k, time) ;
        NC_CHAR v:vector_components = "u v" ;
        NC_CHAR v:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/LCNSMP01/" ;
        NC_CHAR v:coordinates = "time zc latitude longitude" ;
        NC_CHAR v:short_name = "v" ;
        NC_CHAR v:standard_name = "northward_sea_water_velocity" ;
        NC_CHAR v:vector_name = "Currents" ;
        NC_CHAR v:aggregation = "Daily" ;
        NC_CHAR v:units = "ms-1" ;
        NC_CHAR v:long_name = "Northward current" ;
        NC_INT v:_ChunkSizes = 1, 1, 133, 491 ;
    NC_DOUBLE zc(k) ;
        NC_CHAR zc:units = "m" ;
        NC_CHAR zc:positive = "up" ;
        NC_CHAR zc:long_name = "Z coordinate" ;
        NC_CHAR zc:axis = "Z" ;
        NC_CHAR zc:coordinate_type = "Z" ;
        NC_CHAR zc:_CoordinateAxisType = "Height" ;
        NC_CHAR zc:_CoordinateZisPositive = "up" ;
    NC_DOUBLE time(time) ;
        NC_CHAR time:units = "days since 1990-01-01 00:00:00 +10" ;
        NC_CHAR time:long_name = "Time" ;
        NC_CHAR time:standard_name = "time" ;
        NC_CHAR time:coordinate_type = "time" ;
        NC_CHAR time:puv__uom = "http://vocab.nerc.ac.uk/collection/P06/current/UTAA/" ;
        NC_CHAR time:calendar = "gregorian" ;
        NC_CHAR time:_CoordinateAxisType = "Time" ;
        NC_INT time:_ChunkSizes = 1024 ;
    NC_DOUBLE latitude(latitude) ;
        NC_CHAR latitude:units = "degrees_north" ;
        NC_CHAR latitude:long_name = "Latitude" ;
        NC_CHAR latitude:standard_name = "latitude" ;
        NC_CHAR latitude:coordinate_type = "latitude" ;
        NC_CHAR latitude:projection = "geographic" ;
        NC_CHAR latitude:puv__ofProperty = "http://vocab.nerc.ac.uk/collection/S06/current/S0600045/" ;
        NC_CHAR latitude:puv__uom = "http://vocab.nerc.ac.uk/collection/P06/current/DEGN/" ;
        NC_CHAR latitude:_CoordinateAxisType = "Lat" ;
    NC_DOUBLE longitude(longitude) ;
        NC_CHAR longitude:puv__uom = "http://vocab.nerc.ac.uk/collection/P06/current/DEGE/" ;
        NC_CHAR longitude:units = "degrees_east" ;
        NC_CHAR longitude:long_name = "Longitude" ;
        NC_CHAR longitude:standard_name = "longitude" ;
        NC_CHAR longitude:coordinate_type = "longitude" ;
        NC_CHAR longitude:projection = "geographic" ;
        NC_CHAR longitude:_CoordinateAxisType = "Lon" ;
    NC_FLOAT mean_wspeed(longitude, latitude, time) ;
        NC_CHAR mean_wspeed:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/ESEWMPXX/" ;
        NC_CHAR mean_wspeed:coordinates = "time latitude longitude" ;
        NC_CHAR mean_wspeed:units = "ms-1" ;
        NC_CHAR mean_wspeed:short_name = "mean_wspeed" ;
        NC_CHAR mean_wspeed:aggregation = "mean_speed" ;
        NC_CHAR mean_wspeed:standard_name = "mean_wind_speed" ;
        NC_CHAR mean_wspeed:long_name = "mean_wind_speed" ;
        NC_INT mean_wspeed:_ChunkSizes = 1, 133, 491 ;
    NC_FLOAT eta(longitude, latitude, time) ;
        NC_CHAR eta:puv__parameter = "https://vocab.nerc.ac.uk/collection/P01/current/ASLVMP01/" ;
        NC_CHAR eta:coordinates = "time latitude longitude" ;
        NC_CHAR eta:short_name = "eta" ;
        NC_CHAR eta:standard_name = "sea_surface_height_above_geoid" ;
        NC_CHAR eta:aggregation = "Daily" ;
        NC_CHAR eta:units = "metre" ;
        NC_CHAR eta:positive = "up" ;
        NC_CHAR eta:long_name = "Surface elevation" ;
        NC_INT eta:_ChunkSizes = 1, 133, 491 ;
    NC_FLOAT wspeed_u(longitude, latitude, time) ;
        NC_CHAR wspeed_u:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/ESEWMPXX/" ;
        NC_CHAR wspeed_u:coordinates = "time latitude longitude" ;
        NC_CHAR wspeed_u:short_name = "wspeed_u" ;
        NC_CHAR wspeed_u:aggregation = "Daily" ;
        NC_CHAR wspeed_u:units = "ms-1" ;
        NC_CHAR wspeed_u:long_name = "eastward_wind" ;
        NC_INT wspeed_u:_ChunkSizes = 1, 133, 491 ;
    NC_FLOAT wspeed_v(longitude, latitude, time) ;
        NC_CHAR wspeed_v:puv__parameter = "http://vocab.nerc.ac.uk/collection/P01/current/ESNSMPXX/" ;
        NC_CHAR wspeed_v:coordinates = "time latitude longitude" ;
        NC_CHAR wspeed_v:short_name = "wspeed_v" ;
        NC_CHAR wspeed_v:aggregation = "Daily" ;
        NC_CHAR wspeed_v:units = "ms-1" ;
        NC_CHAR wspeed_v:long_name = "northward_wind" ;
        NC_INT wspeed_v:_ChunkSizes = 1, 133, 491 ;

// global attributes:
        NC_CHAR :Conventions = "CF-1.0" ;
        NC_CHAR :Parameter_File_Revision = "$Revision: 1753 $" ;
        NC_CHAR :Run_ID = "2.1" ;
        NC_CHAR :Run_code = "GBR4 Hydro|G0.00|H2.10|S0.00|B0.00" ;
        NC_CHAR :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention" ;
        NC_CHAR :aims_ncaggregate_buildDate = "2023-01-25T03:48:20+10:00" ;
        NC_CHAR :aims_ncaggregate_datasetId = "products__ncaggregate__ereefs__gbr4_v2__daily-monthly/EREEFS_AIMS-CSIRO_gbr4_v2_hydro_daily-monthly-2022-12" ;
        NC_CHAR :aims_ncaggregate_firstDate = "2022-12-01T00:00:00+10:00" ;
        NC_CHAR :aims_ncaggregate_inputs = "[products__ncaggregate__ereefs__gbr4_v2__raw/EREEFS_AIMS-CSIRO_gbr4_v2_hydro_raw_2022-12::MD5:bd27b033d40e598c20348044720deb73]" ;
        NC_CHAR :aims_ncaggregate_lastDate = "2022-12-31T00:00:00+10:00" ;
        NC_CHAR :bald__isPrefixedBy = "prefix_list" ;
        NC_CHAR :date_created = "Sun Dec 11 21:24:39 2022" ;
        NC_CHAR :description = "Aggregation of raw hourly input data (from eReefs AIMS-CSIRO GBR4 Hydrodynamic v2 subset) to daily means. Also calculates mean magnitude of wind and ocean current speeds. Data is regridded from curvilinear (per input data) to rectilinear via inverse weighted distance from up to 4 closest cells." ;
        NC_CHAR :ems_version = "v1.4.0 rev(6949)" ;
        NC_CHAR :history = "2023-01-24T10:49:00+10:00: vendor: AIMS; processing: None summaries
2023-01-25T03:48:20+10:00: vendor: AIMS; processing: Daily summaries" ;
        NC_CHAR :metadata_link = "https://eatlas.org.au/data/uuid/350aed53-ae0f-436e-9866-d34db7f04d2e" ;
        NC_CHAR :paramfile = "./prm/gbr4_hydro_nrt.prm" ;
        NC_CHAR :paramhead = "GBR 4km resolution grid" ;
        NC_CHAR :prefix_list_puv__ = "https://w3id.org/env/puv#" ;
        NC_CHAR :prefix_list_qudt__ = "http://qudt.org/vocab/unit/" ;
        NC_CHAR :technical_guide_link = "https://eatlas.org.au/pydio/public/aims-ereefs-platform-technical-guide-to-derived-products-from-csiro-ereefs-models-pdf" ;
        NC_CHAR :technical_guide_publish_date = "2020-08-18" ;
        NC_CHAR :title = "eReefs AIMS-CSIRO GBR4 Hydrodynamic v2 daily aggregation" ;
        NC_CHAR :DODS_EXTRA.Unlimited_Dimension = "time" ;
}</code></pre>
</div>
</div>
</details>
</section>
<section id="extract-data" class="level2">
<h2 class="anchored" data-anchor-id="extract-data">Extract data</h2>
<p>Now that we have an open connection to a file on the server we need to extract the daily mean temperature at 1.5m depth for the 10th of December.</p>
<p>From the <code>summary</code> output above we can see that the variable corresponding to temperature is: <span class="math inline">\(\texttt{ temp(longitude, latitude, k, time)}\)</span>.</p>
<p>The dimensions for temperature are in brackets. This means that there is a temperature value for every combination of longitude, latitude, depth (k) and time. We can now see why these NetCDF files are so large.</p>
<p>To extract data from the file we will use the function</p>
<p><code>RNetCDF::var.get.nc(ncfile, variable, start=NA, count=NA, ...)</code></p>
<p>We need to give the function:</p>
<ul>
<li><code>ncfile</code>: a NetCDF file connection; in our case <code>dailyAggDec22.nc</code>.</li>
<li><code>variable</code>: the name or id of the data variable we wish to extract; in our case <code>"temp"</code>.</li>
<li><code>start</code>: a vector of indices of where to start getting data, one for each dimension of the variable. Since we have <span class="math inline">\(\texttt{temp(longitude, latitude, k, time)}\)</span> we need to tell the function where to start getting data along each of the four dimensions.</li>
<li><code>count</code>: similar to start, but specifying the number of temperature values to extract along each dimension.</li>
</ul>
<p>Let’s look at how to construct our <code>start</code> and <code>count</code> vectors.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The default values of <code>start</code> and <code>count</code> are <code>NA</code>, in which case all data for the given <code>variable</code> will be extracted.</p>
</div>
</div>
</div>
<p><strong>Depth</strong>: Starting with depth is easy because we have a constant value of interest (1.5 m). The index <code>k</code> corresponds to different depths as shown in the table below, where we see that for the 4km models <code>k=16</code> maps to a depth of 1.5 m.</p>
<details>
<summary>
Table of eReefs depths corresponding to index <code>k</code>
</summary>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Index k (R)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Index k (Python)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hydrodynamic 1km model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hydrodynamic &amp; BioGeoChemical 4km models</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right; color: grey !important;">0</td>
<td style="text-align: right;">-140.00</td>
<td style="text-align: right;">-145.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right; color: grey !important;">1</td>
<td style="text-align: right;">-120.00</td>
<td style="text-align: right;">-120.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right; color: grey !important;">2</td>
<td style="text-align: right;">-103.00</td>
<td style="text-align: right;">-103.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right; color: grey !important;">3</td>
<td style="text-align: right;">-88.00</td>
<td style="text-align: right;">-88.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right; color: grey !important;">4</td>
<td style="text-align: right;">-73.00</td>
<td style="text-align: right;">-73.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right; color: grey !important;">5</td>
<td style="text-align: right;">-60.00</td>
<td style="text-align: right;">-60.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right; color: grey !important;">6</td>
<td style="text-align: right;">-49.00</td>
<td style="text-align: right;">-49.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right; color: grey !important;">7</td>
<td style="text-align: right;">-39.50</td>
<td style="text-align: right;">-39.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right; color: grey !important;">8</td>
<td style="text-align: right;">-31.00</td>
<td style="text-align: right;">-31.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right; color: grey !important;">9</td>
<td style="text-align: right;">-24.00</td>
<td style="text-align: right;">-23.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right; color: grey !important;">10</td>
<td style="text-align: right;">-18.00</td>
<td style="text-align: right;">-17.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right; color: grey !important;">11</td>
<td style="text-align: right;">-13.00</td>
<td style="text-align: right;">-12.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right; color: grey !important;">12</td>
<td style="text-align: right;">-9.00</td>
<td style="text-align: right;">-8.80</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right; color: grey !important;">13</td>
<td style="text-align: right;">-5.25</td>
<td style="text-align: right;">-5.55</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right; color: grey !important;">14</td>
<td style="text-align: right;">-2.35</td>
<td style="text-align: right;">-3.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right; color: grey !important;">15</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: right;">-1.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right; color: grey !important;">16</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.50</td>
</tr>
</tbody>
</table>


</div>
</div>
</details>
<p><strong>Time</strong>: Since we have the daily aggregated data for December 2022, and are interested only in a single day (the 10th), <code>time</code> is also a constant value. From the summary output we can see we have 31 time indexs, these correspond to the day of the month, therefore we want <code>time=10</code>.</p>
<p><strong>Longitude and latitude</strong>: We want temperatures for every available longitude and latitude so we can plot the data across the entire spatial range of the eReefs model. Therefore we want to start at index 1 and count for the entire length of latitude and longitude. To get the lengths we could note the values from the summary output, where we see <span class="math inline">\(\texttt{longitude = 491}\)</span> and <span class="math inline">\(\texttt{latitude = 723}\)</span>. However we could also get the lengths programatically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lon <span class="ot">&lt;-</span> <span class="fu">var.get.nc</span>(dailyAggDec22.nc, <span class="st">"longitude"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>lat <span class="ot">&lt;-</span> <span class="fu">var.get.nc</span>(dailyAggDec22.nc, <span class="st">"latitude"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">length</span>(lon), <span class="fu">length</span>(lat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  length.lon. length.lat.
1         491         723</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Within the eReefs netCDF files, the dimensions <span class="math inline">\(\texttt{longitude, latitude, k, time}\)</span> have corresponding variables <code>longitude</code>, <code>latitude</code>, <code>zc</code>, <code>time</code> (see summary output). Note that we would extract the dimension <span class="math inline">\(\texttt{k}\)</span> variable with <code>var.get.nc(..., variable = "zc")</code>.</p>
</div>
</div>
</div>
<p>Now we are ready to construct our <code>start</code> and <code>count</code> vectors and extract the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SETUP START AND COUNT VECTORS</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Recall the order of the dimensions: (lon, lat, k , time)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We start at lon=1, lat=1, k=16, time=10 and get temps for</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># every lon and lat while holding depth and time constant</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>lon_st <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>lat_st <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>depth_st <span class="ot">&lt;-</span> <span class="dv">16</span>  <span class="co"># index k = 16 --&gt; depth = 1.5 m</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>time_st <span class="ot">&lt;-</span> <span class="dv">10</span>   <span class="co"># index time = 10 --&gt; 10th day of month</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>lon_ct <span class="ot">&lt;-</span> <span class="fu">length</span>(lon) <span class="co"># get temps for all lons and lats</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>lat_ct <span class="ot">&lt;-</span> <span class="fu">length</span>(lat)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>time_ct <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># Hold time and depth constant</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>depth_ct <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>start_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(lon_st, lat_st, depth_st, time_st)  </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>count_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(lon_ct, lat_ct, time_ct, depth_ct)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># EXTRACT DATA</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>temps_10Dec22_1p5m <span class="ot">&lt;-</span> <span class="fu">var.get.nc</span>(</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncfile =</span> dailyAggDec22.nc, </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="st">"temp"</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> start_vector, </span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">count =</span> count_vector</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the size of our extracted data</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>dims <span class="ot">&lt;-</span> <span class="fu">dim</span>(temps_10Dec22_1p5m)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">nrows =</span> dims[<span class="dv">1</span>], <span class="at">ncols =</span> dims[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  nrows ncols
1   491   723</code></pre>
</div>
</div>
</section>
<section id="close-file-connection" class="level2">
<h2 class="anchored" data-anchor-id="close-file-connection">Close file connection</h2>
<p>Now that our extracted data is stored in memory, we should close the connection to the NetCDF file on the server.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">close.nc</span>(dailyAggDec22.nc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="save-the-data" class="level2">
<h2 class="anchored" data-anchor-id="save-the-data">Save the data</h2>
<p>Now that we have our extracted data we may wish to save it for future use. To do this we first convert the data from its current form as a matrix array into a raster, and then save the raster as a netCDF file (GeoTIFF and other formats are also possible).</p>
<p>When converting extracted eReefs data to rasters we need to apply the transpose <code>t()</code> and <code>flip()</code> functions in order to get the correct orientation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>temps_raster <span class="ot">&lt;-</span> temps_10Dec22_1p5m <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>() <span class="sc">|&gt;</span>   <span class="co"># transpose temps matrix</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">raster</span>(  <span class="co"># create raster</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">xmn =</span> <span class="fu">min</span>(lon), <span class="at">xmx =</span> <span class="fu">max</span>(lon), </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymn =</span> <span class="fu">min</span>(lat), <span class="at">ymx =</span> <span class="fu">max</span>(lat), </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">crs =</span> <span class="fu">CRS</span>(<span class="st">"+init=epsg:4326"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flip</span>(<span class="at">direction =</span> <span class="st">'y'</span>) <span class="co"># flip the raster</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in CPL_crs_from_input(x): GDAL Message 1: +init=epsg:XXXX syntax is
deprecated. It might return a CRS with a non-EPSG compliant axis order.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>temps_raster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 723, 491, 354993  (nrow, ncol, ncell)
resolution : 0.0299389, 0.02995851  (x, y)
extent     : 142.1688, 156.8688, -28.69602, -7.036022  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : layer 
values     : 22.08588, 32.48817  (min, max)</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>In the code chunk above we used <a href="https://r4ds.hadley.nz/workflow-pipes.html">pipes</a> <code>|&gt;</code>. Pipes are very useful when passing a dataset through a sequence of functions. In the code above we take our extracted temps, transpose them, turn them into a raster, and then flip the raster. The final result is saved to <code>temps_raster</code>.</p>
</div>
</div>
</div>
<p>Now we have our raster (in the correct orientation), saving it is easy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the raster file in the /data subdirectory</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note the '.nc' file extension since we are going to save as netCDF</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>save_file <span class="ot">&lt;-</span> <span class="st">"data/ereefsDailyMeanWaterTemperature_10Dec2022_Depth1p5m.nc"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">writeRaster</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> temps_raster, <span class="co"># what to save</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">filename =</span> save_file, <span class="co"># where to save it</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">format =</span> <span class="st">"CDF"</span>, <span class="co"># what format to save it as</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">overwrite =</span> <span class="cn">TRUE</span> <span class="co"># whether to replace any existing file with the same name</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The <code>raster</code> package uses the <code>ncdf4</code> package to deal with netCDF files. You can install this package by running <code>install.packages("ncdf4")</code> from an R console.</p>
</div>
</div>
</div>
<p>To prove to ourselves that this worked, lets read the file back in and plot it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read back in the saved netCDF file as a raster</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>saved_temps <span class="ot">&lt;-</span> <span class="fu">raster</span>(save_file)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(saved_temps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-temps-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temps-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="basic_server_access_r_files/figure-html/fig-temps-plot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temps-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Extracted eReefs daily aggregated mean temperature at 1.5m depth for 10 December 2022.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hooray! We can now see our saved data plotted in <a href="#fig-temps-plot" class="quarto-xref">Figure&nbsp;1</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>